using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace UI.MasterSystemSetup
{
    public partial class frm_MSS_CustomerRequirementViewAll : Form
    {
        public frm_MSS_CustomerRequirementViewAll()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DA.SwireDBEntities dbContext = new DA.SwireDBEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.CustomerRequirements.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.CustomerRequirements.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
