//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aisles
    {
        public int AisleRoomID { get; set; }
        public string RoomID { get; set; }
        public byte Aisle { get; set; }
        public short NumberOfBays { get; set; }
        public short NumberOfDeeps { get; set; }
        public short NumberOfHighs { get; set; }
        public Nullable<int> StoreID { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
