//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int AssignmentID { get; set; }
        public Nullable<System.DateTime> AssigmentDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<int> OtherJobDefinitionID { get; set; }
        public string AssignmentDescription { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool Confirmed { get; set; }
        public string EmployeeFeedback { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public bool AssigmentReject { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public string ConfirmBy { get; set; }
        public Nullable<int> TaskProgress { get; set; }
        public bool Completed { get; set; }
        public Nullable<int> AssignedTo2 { get; set; }
        public Nullable<int> AssignedTo3 { get; set; }
        public bool AssignmentRead { get; set; }
        public Nullable<System.DateTime> AssignmentReadTime { get; set; }
        public byte[] TS { get; set; }
        public Nullable<byte> ConfidentialLevel { get; set; }
        public string OrderNumber { get; set; }
        public string AssignmentNumber { get; set; }
    }
}
