//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;

    public partial class BillingSummaryDetails
    {
        public int BillingSummaryDetailID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> LastBillingID { get; set; }
        public string BillingRemark { get; set; }
        public int BillingSummaryID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string CustomerCategory { get; set; }

        public virtual BillingSummary BillingSummary { get; set; }
        public virtual Customers Customers { get; set; }
        public string CustomerCategorySymbol { get; set; }
    }
}
