//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetails
    {
        public int BillingDetailID { get; set; }
        public int BillingID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<decimal> ServiceQuantity { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<bool> ManualUpdate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public string BillingDetailRemark { get; set; }

        public virtual Billings Billings { get; set; }
        public virtual ServicesDefinition ServicesDefinition { get; set; }
    }
}
