//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingDetailBreakDown
    {
        public int BillingDetailBreakdownID { get; set; }
        public int BillingID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> BeginC { get; set; }
        public Nullable<int> InC { get; set; }
        public Nullable<int> OutC { get; set; }
        public Nullable<int> CloseC { get; set; }
        public Nullable<decimal> BeginW { get; set; }
        public Nullable<decimal> InW { get; set; }
        public Nullable<decimal> OutW { get; set; }
        public Nullable<decimal> CloseW { get; set; }
        public Nullable<int> BeginP { get; set; }
        public Nullable<int> InP { get; set; }
        public Nullable<int> OutP { get; set; }
        public Nullable<int> CloseP { get; set; }
        public string BillingDetailBreakdownRemark { get; set; }
    }
}
