//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using DA;
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInvoiceDetail
    {
        public int BillingInvoiceDetailID { get; set; }
        public int BillingInvoiceID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> ServiceQuantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> VATPercentage { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public string BillingInvoiceDetailRemark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> BillingDetailID { get; set; }
        public string StoreNumberM3 { get; set; }

        public virtual BillingInvoice BillingInvoice { get; set; }
    }
}
