//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingInvoice()
        {
            this.BillingInvoiceDetails = new HashSet<BillingInvoiceDetail>();
        }

        public int BillingInvoiceID { get; set; }
        public string BillingInvoiceNumber { get; set; }
        public Nullable<int> BillingID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string AccInvNumber { get; set; }
        public string AccInvBatchNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerTaxCode { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public string GrossAmountWording { get; set; }
        public string BillingInvoiceRemark { get; set; }
        public string E_InvoiceNumber { get; set; }
        public string E_InvoiceLink { get; set; }
        public string E_InvoiceControlCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> E_InvoiceUploadTime { get; set; }
        public string E_InvoiceUploadedBy { get; set; }
        public string InvoicePeriod { get; set; }
        public string InvoiceCurrency { get; set; }
        public Nullable<int> CurrencyExchangRate { get; set; }
        public Nullable<int> PaymentDays { get; set; }
        public Nullable<System.DateTime> PaymentLastestDate { get; set; }
        public string PONumber { get; set; }
        public string Buyer { get; set; }
        public Nullable<System.DateTime> BillingInvoiceEndDate { get; set; }
        public bool isDeleted { get; set; }
        public string DeleteReason { get; set; }
        public string M3ExportBy { get; set; }
        public Nullable<System.DateTime> M3ExportTime { get; set; }
        public bool isM3Hold { get; set; }
        public string BillingInvoiceIDHash { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingInvoiceDetail> BillingInvoiceDetails { get; set; }
    }
}
