//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Billings
    {
        public Billings()
        {
            this.BillingDetails = new HashSet<BillingDetails>();
        }

        public int BillingID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime BillingDate { get; set; }
        public System.DateTime BillingFromDate { get; set; }
        public System.DateTime BillingToDate { get; set; }
        public bool Confirmed { get; set; }
        public string BillingRemark { get; set; }
        public bool Selected { get; set; }
        public bool Invoiced { get; set; }
        public string InvoiceRemark { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceInputBy { get; set; }
        public Nullable<System.DateTime> InvoiceInputDate { get; set; }
        public Nullable<System.DateTime> BillingCreatedTime { get; set; }
        public string BillingCreatedBy { get; set; }
        public string BillingNumber { get; set; }
        public bool IsDeleted { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<BillingDetails> BillingDetails { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
