//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlastFreezerDetails
    {
        public int BlastFreezerDetailsID { get; set; }
        public int BlastFreezerID { get; set; }
        public System.DateTime RecordTime { get; set; }
        public short SampleNumber { get; set; }
        public double SampleTemp { get; set; }
        public string Remark { get; set; }
    
        public virtual BlastFreezers BlastFreezers { get; set; }
    }
}
