//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessTrips
    {
        public int BusinessTripID { get; set; }
        public string BusinessTripNumber { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> Endtime { get; set; }
        public bool BikeUse { get; set; }
        public Nullable<int> BikeMilage { get; set; }
        public bool BikeParking { get; set; }
        public Nullable<float> ParkingPrice { get; set; }
        public string WhereTo { get; set; }
        public string Purpose { get; set; }
        public bool LunchRequired { get; set; }
        public string AuthorisedNameBy { get; set; }
        public Nullable<System.DateTime> AuthorisedTime { get; set; }
        public bool TripConfirmed { get; set; }
        public bool GuardConfirmed { get; set; }
        public Nullable<System.DateTime> GuardTime { get; set; }
        public string AuthorisedCreated { get; set; }
        public string BusinessTripCategory { get; set; }
        public byte PhoneUsed { get; set; }
        public byte[] ts { get; set; }
    }
}
