//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Opportunities
    {
        public System.Guid OpportunityID { get; set; }
        public string OpportunityNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string OpportunityName { get; set; }
        public bool Deleted { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Probability { get; set; }
        public string AssignedToUser { get; set; }
        public string OpportunityType { get; set; }
        public string SalesStage { get; set; }
        public Nullable<int> ForecastingPallets { get; set; }
        public Nullable<int> ForecastingCartons { get; set; }
        public Nullable<int> ForecastingUnits { get; set; }
        public Nullable<decimal> ForecastingWeights { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public string Emails { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Contacts { get; set; }
        public string Website { get; set; }
        public Nullable<int> CustomerCategory { get; set; }
        public string CustomerType { get; set; }
    }
}
