//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_OpportunityDetails
    {
        public int OpportunitieDetailID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime PlanningDate { get; set; }
        public Nullable<int> Pallets { get; set; }
        public Nullable<decimal> Weights { get; set; }
        public Nullable<int> Cartons { get; set; }
        public Nullable<int> Units { get; set; }
        public string Remark { get; set; }
        public System.Guid OpportunityID { get; set; }
        public byte[] ts { get; set; }
        public string CategoryDetails { get; set; }
    }
}
