//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSalesInvoices
    {
        public CustomerSalesInvoices()
        {
            this.CustomerSalesInvoiceDetails = new HashSet<CustomerSalesInvoiceDetails>();
        }
    
        public int CustomerSalesInvoiceID { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime CustomerSalesInvoiceDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public string CustomerSalesInvoiceRemark { get; set; }
        public Nullable<float> TotalAmount { get; set; }
        public Nullable<float> DiscountAmount { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<int> CustomerClientID { get; set; }
        public string CustomerClientRepresentative { get; set; }
        public string CustomerSalesOrderNumber { get; set; }
        public Nullable<System.DateTime> CustomerSalesOrderDate { get; set; }
        public string InvoiceOfficialNumber { get; set; }
        public string InvoiceOfficialSerieName { get; set; }
        public int CustomerSalesContractID { get; set; }
        public Nullable<bool> CustomerSalesInvoiceConfirmed { get; set; }
        public byte[] ts { get; set; }
        public string CustomerPurchasingOrderNumber { get; set; }
        public Nullable<short> CustomerSalesOrderReturn { get; set; }
        public string OrderReference { get; set; }
        public string TruckNumber { get; set; }
        public string DriverPhoneNumber { get; set; }
        public Nullable<int> PlanDate { get; set; }
        public Nullable<int> TransporterID { get; set; }
        public string TransferName { get; set; }
        public Nullable<bool> Logger { get; set; }
    
        public virtual CustomerClients CustomerClients { get; set; }
        public virtual CustomerSalesContracts CustomerSalesContracts { get; set; }
        public virtual ICollection<CustomerSalesInvoiceDetails> CustomerSalesInvoiceDetails { get; set; }
    }
}
