//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSalesInvoiceDetails
    {
        public CustomerSalesInvoiceDetails()
        {
            this.CustomerSalesInvoicePallets = new HashSet<CustomerSalesInvoicePallets>();
        }
    
        public int CustomerSalesInvoiceDetailID { get; set; }
        public int CustomerSalesInvoiceID { get; set; }
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<float> OrderQuantity { get; set; }
        public Nullable<int> OrderUnitQuanity { get; set; }
        public Nullable<int> DispatchedQuantity { get; set; }
        public string InvoiceUnit { get; set; }
        public float InvoicePrice { get; set; }
        public float InvoiceQuantity { get; set; }
        public string CustomerSalesInvoiceDetailRemark { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> DispatchingProductID { get; set; }
        public byte[] ts { get; set; }
        public Nullable<byte> CustomerDispatchType { get; set; }
        public Nullable<int> UnitPerPackage { get; set; }
        public Nullable<short> OddPieceQuanity { get; set; }
        public Nullable<bool> Promotion { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<float> ProductDiscountPercentage { get; set; }
        public Nullable<int> OrderUnitQuanityCheck { get; set; }
        public Nullable<int> CustomerSalesContractDetailID { get; set; }
        public Nullable<bool> Unfreeze { get; set; }
        public Nullable<double> OrderQuantityBook { get; set; }
    
        public virtual CustomerSalesInvoices CustomerSalesInvoices { get; set; }
        public virtual ICollection<CustomerSalesInvoicePallets> CustomerSalesInvoicePallets { get; set; }
    }
}
