//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSalesPromotionDetails
    {
        public CustomerSalesPromotionDetails()
        {
            this.CustomerSalesPromotionProducts = new HashSet<CustomerSalesPromotionProducts>();
        }
    
        public int CustomerSalesPromotionDetailID { get; set; }
        public int CustomerSalesPromotionID { get; set; }
        public int ProductID { get; set; }
        public string SalesProductName { get; set; }
        public string CustomerSalesPromotionDetailRemark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public byte[] ts { get; set; }
        public string ProductCode { get; set; }
    
        public virtual CustomerSalesPromotions CustomerSalesPromotions { get; set; }
        public virtual ICollection<CustomerSalesPromotionProducts> CustomerSalesPromotionProducts { get; set; }
    }
}
