//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSupplier
    {
        public int CustomerSupplierID { get; set; }
        public int CustomerID { get; set; }
        public string CustomerSupplierCode { get; set; }
        public string CustomerSupplierName { get; set; }
        public string CustomerSupplierAddress { get; set; }
        public string CustomerSupplierPhone { get; set; }
        public string CustomerSupplierEmail { get; set; }
        public string CustomerSupplierContacts { get; set; }
        public string CustomerSupplierDescriptions { get; set; }
        public string CustomerSupplierTaxName { get; set; }
        public string CustomerSupplierTaxCode { get; set; }
        public string CustomerSupplierDeliveryAddress { get; set; }
        public Nullable<int> CustomerSupplierMainID { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public byte[] TS { get; set; }
    }
}
