//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    
    public partial class CustomerClients
    {
        public CustomerClients()
        {
            this.CustomerSalesContracts = new HashSet<CustomerSalesContracts>();
            this.CustomerSalesInvoices = new HashSet<CustomerSalesInvoices>();
        }

        public int CustomerClientID { get; set; }
        public int CustomerID { get; set; }
        public string CustomerClientCode { get; set; }
        public string CustomerClientName { get; set; }
        public string CustomerClientAddress { get; set; }
        public string CustomerClientPhone { get; set; }
        public string CustomerClientEmail { get; set; }
        public string CustomerClientContacts { get; set; }
        public string CustomerClientDescriptions { get; set; }
        public string CustomerClientTaxName { get; set; }
        public string CustomerClientTaxCode { get; set; }
        public string CustomerClientDeliveryAddress { get; set; }
        public Nullable<int> CustomerClientMainID { get; set; }
        public Nullable<int> CustomerClientCodeFBV { get; set; }
        public string CustomerClientMain { get; set; }
        public Nullable<float> DiscountAmountPercentage { get; set; }
        public Nullable<short> CustomerClientCreditTerm { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public string CustomerClientBuyer { get; set; }
        public byte[] TS { get; set; }
        public Nullable<float> Shelflife { get; set; }
        public string AddressDistrict { get; set; }
        public string AddressProvince { get; set; }
        public string AddressMapCoordinates { get; set; }
        public Nullable<int> DefaultRoute { get; set; }
        public Nullable<float> DeadlineNumber { get; set; }
        public string DeliveryType { get; set; }
        public string ClientDeliveryRemark { get; set; }
        public string ClientPaymentMethod { get; set; }
        public string ClientGroupName { get; set; }
        public Nullable<byte> DispatchingMethodID { get; set; }
        public string ClientAddressZone { get; set; }

        public virtual Customers Customers { get; set; }
         [XmlIgnoreAttribute]
        public virtual ICollection<CustomerSalesContracts> CustomerSalesContracts { get; set; }
         [XmlIgnoreAttribute]
        public virtual ICollection<CustomerSalesInvoices> CustomerSalesInvoices { get; set; }
    }
}
