//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInquiryService
    {
        public int CustomerInquiryServiceID { get; set; }
        public int CustomerInquiryDetailID { get; set; }
        public int ServiceID { get; set; }
        public string ServiceQuantity { get; set; }
        public string CustomerInquiryServiceRemark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string ServiceScopeOfWork { get; set; }
        public string ServiceScopeOfWorkVietnam { get; set; }
    
        public virtual CustomerInquiryDetail CustomerInquiryDetail { get; set; }
    }
}
