//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Billings = new HashSet<Billings>();
            this.BillingSummaryDetails = new HashSet<BillingSummaryDetails>();
            this.CustomerClients = new HashSet<CustomerClients>();
            this.CustomerSalesContracts = new HashSet<CustomerSalesContracts>();
            this.DispatchingOrders = new HashSet<DispatchingOrders>();
            this.EDI_Orders = new HashSet<EDI_Orders>();
            this.OperatingCostDetailByCustomers = new HashSet<OperatingCostDetailByCustomers>();
            this.OtherService = new HashSet<OtherService>();
            this.ReceivingOrders = new HashSet<ReceivingOrders>();
        }

        public int CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public int CustomerMainID { get; set; }
        public string Initial { get; set; }
        public string Address { get; set; }
        public string CustomerType { get; set; }
        public string PrimaryContact { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Fax2 { get; set; }
        public string Email { get; set; }
        public string OtherContacts { get; set; }
        public string MarketingInfor { get; set; }
        public string CustomerInvoiceName { get; set; }
        public string CustomerInvoiceAddress { get; set; }
        public string CustomerInvoiceTaxCode { get; set; }
        public Nullable<bool> CustomerDiscontinued { get; set; }
        public byte CustomerCategory { get; set; }
        public Nullable<byte> CustomerGroup { get; set; }
        public Nullable<bool> CustomerByExpiryDate { get; set; }
        public Nullable<bool> SendNote { get; set; }
        public Nullable<int> CustomerSubID { get; set; }
        public Nullable<bool> Hold { get; set; }
        public string HoldMessage { get; set; }
        public byte[] ts { get; set; }
        public Nullable<bool> HomeLocationChange { get; set; }
        public Nullable<bool> DispatchingByClient { get; set; }
        public string CustomerPalletType { get; set; }
        public string Website { get; set; }
        public string EmailBilling { get; set; }
        public Nullable<byte> CustomerDispatchType { get; set; }
        public Nullable<bool> IsAllowEDI { get; set; }
        public Nullable<int> HoldLimitWeight { get; set; }
        public string CustomerTaxGroup { get; set; }
        public Nullable<bool> BarcodeScanRequire { get; set; }
        public Nullable<short> DefaultProcessTime { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<byte> CustomerPotentialCategoryID { get; set; }
        public Nullable<int> HomeLocation1 { get; set; }
        public Nullable<int> HomeLocation2 { get; set; }
        public Nullable<int> CustomerAssignedTo { get; set; }
        public string InvoiceSendEmail { get; set; }
        public Nullable<int> CustomerReportType { get; set; }
        public Nullable<int> ERPProductLength { get; set; }
        public Nullable<bool> isKPIReportRequire { get; set; }
        public Nullable<int> CustomerMainOnReport { get; set; }
        public Nullable<bool> AllowCartonWeightScanOut { get; set; }
        public Nullable<bool> AllowKGRDirectPick { get; set; }
        public string Token { get; set; }
        public string UserName { get; set; }
        public string Passwords { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string BillingInstructions { get; set; }
        public Nullable<System.DateTime> BillingInstructionUpdateTime { get; set; }
        public Nullable<int> VATPercentage { get; set; }
        public string CustomerNumberM3 { get; set; }
        public Nullable<int> CustomerMainInvoiceID { get; set; }
        public Nullable<int> CustomerMainContractID { get; set; }

        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string LSPCode { get; set; }
        public Nullable<bool> isAllowDataIntegration { get; set; }

        [XmlIgnoreAttribute]
        public virtual ICollection<Billings> Billings { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<BillingSummaryDetails> BillingSummaryDetails { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<CustomerClients> CustomerClients { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<CustomerSalesContracts> CustomerSalesContracts { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<DispatchingOrders> DispatchingOrders { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<EDI_Orders> EDI_Orders { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<OperatingCostDetailByCustomers> OperatingCostDetailByCustomers { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<OtherService> OtherService { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<ReceivingOrders> ReceivingOrders { get; set; }
    }
}
