//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;

    public partial class CustomerQuotationDetail
    {
        public int QuotationDetailID { get; set; }
        public int QuotationID { get; set; }
        public Nullable<int> CustomerInquiryServiceID { get; set; }
        public string UnitMeasurement { get; set; }
        public string ServiceDescription { get; set; }
        public string QuotationDetailRemark { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public int ServiceID { get; set; }
        public string CustomerComments { get; set; }
        public string ServiceScopeOfWork { get; set; }
        public string ServiceNameVietnamese { get; set; }
        public string ServiceScopeOfWorkVietnam { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<decimal> EstimatedMonthlyVolume { get; set; }
        public decimal EstimatedTotal
        {
            get
            {
                return Convert.ToDecimal(this.UnitRate) * Convert.ToDecimal(this.EstimatedMonthlyVolume) * 12;
            }
        }
        public Nullable<int> LineNumber { get; set; }
        public Nullable<byte> VATPercentage { get; set; }
        public string ServiceNameInvoiced { get; set; }

        public virtual ServicesDefinition ServicesDefinition { get; set; }
        public virtual CustomerQuotation CustomerQuotation { get; set; }
    }
}
