//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerInquiry()
        {
            this.CustomerInquiryDetails = new HashSet<CustomerInquiryDetail>();
        }
    
        public int CustomerInquiryID { get; set; }
        public string CustomerInquiryNumber { get; set; }
        public Nullable<System.DateTime> CustomerInquiryDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CustomerMainID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CustomerInquiryRemark { get; set; }
        public string StoreID { get; set; }
        public Nullable<short> CustomerInquiryStatus { get; set; }
        public Nullable<int> CustomerCategoryID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInquiryDetail> CustomerInquiryDetails { get; set; }
    }
}
