//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProperties
    {
        public short CustomerID { get; set; }
        public bool Basket { get; set; }
        public bool Pallet { get; set; }
        public string Remark { get; set; }
    }
}
