//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerServiceCosting
    {
        public CustomerServiceCosting()
        {
            this.CustomerServiceCostingDetails = new HashSet<CustomerServiceCostingDetails>();
        }
    
        public int CustomerServiceCostingID { get; set; }
        public int CustomerID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime CostingDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CustomerServiceCostingRemark { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ServiceDetailDescription { get; set; }
        public Nullable<System.DateTime> ServiceProvidedDate { get; set; }
        public Nullable<float> TotalServiceQuantity { get; set; }
        public Nullable<float> TotalCalculatedCost { get; set; }
        public Nullable<float> UnitCost { get; set; }
        public Nullable<float> WorkerDailyProductivity { get; set; }
        public Nullable<float> ProposedWorkerRate { get; set; }
        public Nullable<float> ProposedOverheadMargin { get; set; }
        public Nullable<float> ProposedServicePrice { get; set; }
        public Nullable<float> ActualProposedWorkerRate { get; set; }
        public string CustomerServiceCostingProcess { get; set; }
        public string CustomerServiceCostNumber { get; set; }
        public string ISOFormNumber { get; set; }
    
        public virtual ServicesDefinition ServicesDefinition { get; set; }
        public virtual ICollection<CustomerServiceCostingDetails> CustomerServiceCostingDetails { get; set; }
    }
}
