//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInquiryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerInquiryDetail()
        {
            this.CustomerInquiryServices = new HashSet<CustomerInquiryService>();
        }

        public int CustomerInquiryDetailID { get; set; }
        public Nullable<int> CustomerInquiryID { get; set; }
        public Nullable<int> CustomerInquiryProductDefinitionID { get; set; }
        public Nullable<int> CustomerInquiryQuantity { get; set; }
        public string CustomerInquiryDetailRemark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string TemperatureRange { get; set; }
        public string HumidityRange { get; set; }
        public string StorageRoom { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerInquiryService> CustomerInquiryServices { get; set; }
        public virtual CustomerInquiry CustomerInquiry { get; set; }
    }
}
