//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerForecast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerForecast()
        {
            this.CustomerForecastDetails = new HashSet<CustomerForecastDetail>();
        }
    
        public int CustomerForecastID { get; set; }
        public int CustomerID { get; set; }
        public int OperationCostMonthlyID { get; set; }
        public Nullable<decimal> DailyStockWeight { get; set; }
        public Nullable<int> DailyStockPallet { get; set; }
        public Nullable<decimal> MonthlyHandlingWeight { get; set; }
        public Nullable<int> MonthlyHandlingPallet { get; set; }
        public Nullable<int> MonthlyNumberTransactions { get; set; }
        public string CustomerForecastRemark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerForecastDetail> CustomerForecastDetails { get; set; }
        public virtual CustomerForecast CustomerForecasts1 { get; set; }
        public virtual CustomerForecast CustomerForecast1 { get; set; }
    }
}
