//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerKPIRecording
    {
        public int CustomerKPIRecordingID { get; set; }
        public int CustomerID { get; set; }
        public int OperatingCostMonthlyID { get; set; }
        public int CustomerKPICategoryID { get; set; }
        public decimal RecordedKPIQuantity { get; set; }
        public Nullable<decimal> ActualRecordedQuantity { get; set; }
        public Nullable<decimal> RelatedActivityQuantity { get; set; }
        public string CustomerKPIRecordingRemark { get; set; }
    }
}
