//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerForecastDetail
    {
        public int CustomerForecastDetailID { get; set; }
        public int CustomerForecastID { get; set; }
        public int ServiceID { get; set; }
        public decimal ServiceQuantity { get; set; }
        public string ForecastDetailRemark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual CustomerForecast CustomerForecast { get; set; }
    }
}
