//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSalesInvoicePallets
    {
        public int CustomerSalesInvoicePalletID { get; set; }
        public int CustomerSalesInvoiceDetailID { get; set; }
        public short PlanQuantity { get; set; }
        public string PalletRemark { get; set; }
        public bool OnHold { get; set; }
        public Nullable<int> PalletID { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<float> SelfLifePercentage { get; set; }
        public string LocationNumber { get; set; }
        public Nullable<short> AfterDPQuantity { get; set; }
        public byte[] ts { get; set; }
        public string CustomerRef { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public int OrderUnitQuantity { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public int OrderUnitQuantityBook { get; set; }
    
        public virtual CustomerSalesInvoiceDetails CustomerSalesInvoiceDetails { get; set; }
    }
}
