//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInquiryProduct
    {
        public int CustomerInquiryDetailID { get; set; }
        public Nullable<int> CustomerInquiryID { get; set; }
        public Nullable<int> CustomerInquiryServiceDefinitionID { get; set; }
        public Nullable<int> CustomerInquiryQuantity { get; set; }
        public string CustomerInquiryDetailRemark { get; set; }
        public Nullable<int> CustomerInquiryStorageConditions { get; set; }
    }
}
