//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSalesContractDetails
    {
        public int CustomerSalesContractDetailID { get; set; }
        public int CustomerSalesContractID { get; set; }
        public int ProductID { get; set; }
        public string SalesProductName { get; set; }
        public float SalesPrice { get; set; }
        public string SalesUnit { get; set; }
        public Nullable<int> SalesUnitPerPackage { get; set; }
        public string CurrencyID { get; set; }
        public string CustomerSalesContractDetailRemark { get; set; }
        public byte[] ts { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string SalesProductCode { get; set; }
        public string SalesProductCode2 { get; set; }
    
        public virtual CustomerSalesContracts CustomerSalesContracts { get; set; }
    }
}
