//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSalesPromotions
    {
        public CustomerSalesPromotions()
        {
            this.CustomerSalesPromotionDetails = new HashSet<CustomerSalesPromotionDetails>();
        }
    
        public int CustomerSalesPromotionID { get; set; }
        public int CustomerSalesContractID { get; set; }
        public System.DateTime CustomerSalesPromotionDate { get; set; }
        public System.DateTime CustomerSalesPromotionFromDate { get; set; }
        public System.DateTime CustomerSalesPromotionToDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CustomerSalesPromotionRemark { get; set; }
        public string CustomerSalesPromotionName { get; set; }
    
        public virtual ICollection<CustomerSalesPromotionDetails> CustomerSalesPromotionDetails { get; set; }
    }
}
