//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerQuotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerQuotation()
        {
            this.CustomerQuotationDetails = new HashSet<CustomerQuotationDetail>();
        }

        public int QuotationID { get; set; }
        public string QuotationNumber { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public int CustomerMainID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string QuotationRemark { get; set; }
        public string ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewTime { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public string ReviewRemark { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> CustomerInquiryID { get; set; }
        public Nullable<int> QuotationStatus { get; set; }
        public string CustomerResponse { get; set; }
        public string BDQuotationNumber { get; set; }
        public Nullable<int> PreviousContractID { get; set; }
        public string ValidPeriod { get; set; }
        public string CustomerRepresentative { get; set; }
        public string CustomerRepresentativePosition { get; set; }
        public string VATDescriptionVietnam { get; set; }
        public string VATDescription { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerQuotationDetail> CustomerQuotationDetails { get; set; }
    }
}
