//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInquiryProductDefinition
    {
        public int CustomerInquiryProductDefinitionID { get; set; }
        public string ProductDescriptions { get; set; }
        public string ProductDescriptionVN { get; set; }
        public string StorageRoom { get; set; }
        public string StorageRoomVN { get; set; }
        public string TemperatureRange { get; set; }
        public string HumidityRange { get; set; }
        public string OtherRequirement { get; set; }
        public string OtherRequirementVN { get; set; }
    }
}
