//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerComplainDetails
    {
        public int CustomerComplainDetailID { get; set; }
        public int CustomerComplainID { get; set; }
        public string OperationCode { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public string DetailRemark { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<float> EstimatedValueLost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CurrencyUnit { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual CustomerComplainDetails CustomerComplainDetails1 { get; set; }
        public virtual CustomerComplainDetails CustomerComplainDetails2 { get; set; }
    }
}
