//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContacts
    {
        public int CustomerContactID { get; set; }
        public int CustomerMainID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string ContactRemark { get; set; }
        public string JobDescription { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public bool isOnlineReportAllowed { get; set; }
        public string Password { get; set; }
        public System.Guid Salt { get; set; }
        public byte[] EncryptedPassword { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
