//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTask
    {
        public int TaskID { get; set; }
        public string TaskDescription { get; set; }
        public string UserID { get; set; }
        public System.DateTime TaskCreatedTime { get; set; }
        public bool TaskDone { get; set; }
        public string DoneBy { get; set; }
        public Nullable<System.DateTime> DoneTime { get; set; }
        public bool Sticky { get; set; }
        public bool Forguard { get; set; }
    }
}
