//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryOrderDetail
    {
        public int DeliveryOrderDetailID { get; set; }
        public int DeliveryOrderID { get; set; }
        public int DispatchingProductID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<int> TotalPackages { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public string Remark { get; set; }
        public Nullable<byte> DeliveryStatus { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> TotalPackagesActual { get; set; }
    }
}
