//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public int DepartmentID { get; set; }

        public string DepartmentName { get; set; }

        public string DepartmentNameShort { get; set; }

        public string DepartmentNameVietnam { get; set; }

        public int? UserDepartmentDefinitionID { get; set; }

        public int? StoreID { get; set; }

        public string SlackChannel { get; set; }

        public string SlackToken { get; set; }

        public int? WarehouseID { get; set; }

        public string TeamsChannel { get; set; }

        public string TeamsToken { get; set; }

    }
}
