//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchingOrderDetails
    {
        public int DispatchingOrderDetailID { get; set; }
        public int DispatchingLocationID { get; set; }
        public int PalletID { get; set; }
        public short QuantityOfPackages { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<byte> Status { get; set; }
        public byte[] TS { get; set; }
        public Nullable<int> UnitQuantity { get; set; }
        public Nullable<float> PalletWeight { get; set; }
        public string DispatchingOrderDetailRemark { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<bool> CheckBreak { get; set; }
        public string DispatchingScannedBy { get; set; }
        public Nullable<System.DateTime> DispatchingScannedTime { get; set; }
        public string PickingScannedBy { get; set; }
        public Nullable<System.DateTime> PickingScannedTime { get; set; }
        public Nullable<bool> IsWeighting { get; set; }
        public Nullable<bool> IsSyncNavi { get; set; }
        public Nullable<int> NaviQty { get; set; }
        public string NaviLocation { get; set; }
        public string NaviPalletID { get; set; }
        public Nullable<bool> IsSendNavi { get; set; }

        public virtual DispatchingLocations DispatchingLocations { get; set; }
        public virtual Pallets Pallets { get; set; }

    }
}
