//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class DispatchingProducts
    {
        public DispatchingProducts()
        {
            this.DispatchingLocations = new HashSet<DispatchingLocations>();
        }

        public int DispatchingProductID { get; set; }
        public int DispatchingOrderID { get; set; }
        public string ProductNumber { get; set; }
        public string DispatchingOrderNumber { get; set; }
        public string ProductName { get; set; }
        public int ProductID { get; set; }
        public Nullable<short> PackagesPerPallet { get; set; }
        public short TotalPackages { get; set; }
        public Nullable<float> WeightPerPackage { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Remark { get; set; }
        public string UserID { get; set; }
        public Nullable<short> Plts { get; set; }
        public string CustomerRef { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public byte[] TS { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<short> UnitPerPackage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<float> Temperature { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public Nullable<short> PlannedTotalPackages { get; set; }
        public Nullable<decimal> PlannedTotalWeight { get; set; }
        public string InfoUpdateOrder { get; set; }
        public string Packages { get; set; }
        public Nullable<int> Pcs { get; set; }

        public Nullable<bool> IsMoving { get; set; }
        public Nullable<int> EDI_OrderDetailID { get; set; }
        public Nullable<bool> IsWeighting { get; set; }
        public Nullable<int> OtherServiceID { get; set; }

        [XmlIgnoreAttribute]
        public virtual ICollection<DispatchingLocations> DispatchingLocations { get; set; }
        public virtual DispatchingOrders DispatchingOrders { get; set; }
    }
}
