//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    
    public partial class EDI_Orders
    {
        public EDI_Orders()
        {
            this.EDI_OrderDetails = new HashSet<EDI_OrderDetails>();
        }

        public int EDI_OrderID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string CustomerOrderNumber2 { get; set; }
        public string CustomerReference { get; set; }
        public Nullable<System.DateTime> ProcessingTime { get; set; }
        public Nullable<int> ProcessingStatus { get; set; }
        public int OrderType { get; set; }
        public string ProcessingOrderNumber { get; set; }
        public string ProcessedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public bool FileUploaded { get; set; }
        public string FileUploadedCode { get; set; }
        public int TotalQuantity { get; set; }
        public byte[] TS { get; set; }
        public string CustomerClientCode { get; set; }
        public Nullable<byte> CustomerDispatchType { get; set; }
        public string EDIOrderRemark { get; set; }
        public bool CheckDocument { get; set; }
        public string BillTo { get; set; }
        public string DeliveryTo { get; set; }
        public string Phone { get; set; }
        public string InvoiceNo { get; set; }
        public string InVoiceDate { get; set; }
        public string AccountNo { get; set; }
        public string PaymentTerm { get; set; }
        public string AgentNo { get; set; }
        public string Remarks { get; set; }
        public string SONo { get; set; }
        public bool isManualCreated { get; set; }
        public string Client_Name { get; set; }
        public string Address { get; set; }
        public string VehicleNumber { get; set; }
        

        public virtual Customers Customers { get; set; }
         [XmlIgnoreAttribute]
        public virtual ICollection<EDI_OrderDetails> EDI_OrderDetails { get; set; }
    }
}
