//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI_DetailBreakdowns
    {
        public int EDI_DetailBreakDownID { get; set; }
        public Nullable<int> EDI_OrderDetailID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ReceivingOrderDetailID { get; set; }
        public Nullable<int> QuantityMax { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string CustomerRef { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
    
        public virtual EDI_OrderDetails EDI_OrderDetails { get; set; }
    }
}
