//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeReminders
    {
        public int ReminderID { get; set; }
        public string RoomID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ReminderDescription { get; set; }
        public System.DateTime ReminderDate { get; set; }
        public bool ReminderAcknowledged { get; set; }
        public Nullable<System.DateTime> AcknowledgedTime { get; set; }
        public Nullable<int> AcknowledgedBy { get; set; }
        public string ReminderedBy { get; set; }
        public string ReminderNumber { get; set; }
        public Nullable<int> EmployeeKPIDefinitionID { get; set; }
    }
}
