//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Employees
    {
        public Employees()
        {
            this.DailyChecks = new HashSet<DailyChecks>();
            this.EmployeeAnnualHistories = new HashSet<EmployeeAnnualHistories>();
            this.EmployeeAreaResponsibities = new HashSet<EmployeeAreaResponsibities>();
            this.EmployeeHistory = new HashSet<EmployeeHistory>();
            this.EmployeeWorkings = new HashSet<EmployeeWorkings>();
            this.Gate_EmployeeInOut = new HashSet<Gate_EmployeeInOut>();
        }

        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<short> Status { get; set; }
        public string Education { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string IDCardNumber { get; set; }
        public string Email { get; set; }
        public string Photograph { get; set; }
        public bool Active { get; set; }
        public bool ContractPermanent { get; set; }
        public int ManagementLevel { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public int PositionID { get; set; }
        public string VietnamName { get; set; }
        public string BikeNumber { get; set; }
        public bool BikeUse { get; set; }
        public string VietnamPosition { get; set; }
        public string InOutCardNumber { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> Grade { get; set; }
        public Nullable<byte> Department { get; set; }
        public string AddressNow { get; set; }
        public bool PerformanceStatus { get; set; }
        public Nullable<System.DateTime> IDCardIssueDate { get; set; }
        public Nullable<int> StoreID { get; set; }
        public bool Sex { get; set; }
        public byte[] TS { get; set; }
        public string IDCardIssuePlace { get; set; }
        public bool MonthlyAdvanceRequired { get; set; }
        public Nullable<int> MonthlyAdvanceAmount { get; set; }
        public string ContractNumber { get; set; }
        public string PersonnalTaxCode { get; set; }
        public string BankAccountNumber { get; set; }

        public string WorkdayEmployeeID { get; set; }
        public Nullable<System.DateTime> ContractDateFirst { get; set; }
        public string Remark { get; set; }
        public string LunchPlace { get; set; }
        public Nullable<int> ReportTo { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<bool> IsLeave { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<bool> IsOutsourcing { get; set; }
        public string EnglishName { get; set; }


        public Nullable<int> DepartmentTeamID { get; set; }
        public Nullable<int> EmployeeSafetyTeamID { get; set; }
        public string PLUCode { get; set; }

        public Nullable<int> ContractWorkingDays { get; set; }


        [XmlIgnoreAttribute]
        public virtual ICollection<DailyChecks> DailyChecks { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<EmployeeAnnualHistories> EmployeeAnnualHistories { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<EmployeeAreaResponsibities> EmployeeAreaResponsibities { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<EmployeeHistory> EmployeeHistory { get; set; }

        public virtual Positions Positions { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<EmployeeWorkings> EmployeeWorkings { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<Gate_EmployeeInOut> Gate_EmployeeInOut { get; set; }
        public virtual UserAccount UserAccounts { get; set; }
        public string FullName
        {
            get
            {
                return this.LastName + " " + this.FirstName;
            }
        }
    }
}
