//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeChangeHistory
    {
        public int EmployeeChangeHistoryID { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public int EmployeeID { get; set; }
        public string Description { get; set; }
        public string Salary { get; set; }
        public string SalaryResponsibility { get; set; }
        public string SalaryAllowance { get; set; }
        public string SalarySeniority { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ImplementationDate { get; set; }
        public System.DateTime PeriodOfTime { get; set; }
        public Nullable<bool> Delegate { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<int> OldPositionID { get; set; }
        public Nullable<byte> OldShiftID { get; set; }
        public Nullable<byte> OldDepartmentID { get; set; }
        public Nullable<int> OldStoreID { get; set; }
        public Nullable<bool> OldContractPermanent { get; set; }
        public string OldEducation { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> DepartmentID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<bool> ContractPermanent { get; set; }
        public string Education { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public Nullable<byte> OldDepartmentTeamID { get; set; }
        public Nullable<byte> DepartmentTeamID { get; set; }
    }
}
