//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAreaResponsibities
    {
        public int EmployeeAreaID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string RoomID { get; set; }
        public string AreaRemark { get; set; }
        public Nullable<int> StoreID { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
