//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeKPIRecord
    {
        public int EmployeeKPIRecordID { get; set; }
        public int EmployeeKPITargetID { get; set; }
        public System.DateTime EmployeeKPIRecordDate { get; set; }
        public int EmployeeKPIDefinitionID { get; set; }
        public Nullable<decimal> EmployeeKPITargetAmount { get; set; }
        public decimal EmployeeKPIActualAmount { get; set; }
        public bool EmployeeKPIAchieved { get; set; }
        public string EmployeeKPIRecordRemark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
    }
}
