//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOTSupervisors
    {
        public int EmployeeOTSupervisorID { get; set; }
        public System.DateTime EmployeeOTSupervisorDate { get; set; }
        public string AuthorisedBy { get; set; }
        public int EmployeeID { get; set; }
        public float HourQuantity { get; set; }
        public string DayStatus { get; set; }
        public Nullable<bool> SundayHoliday { get; set; }
        public int Gate { get; set; }
        public bool EmployeeOTSupervisorConfirm { get; set; }
        public string Remarks { get; set; }
    }
}
