//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAnnualHistories
    {
        public int EmployeeHistoryID { get; set; }
        public int EmployeeID { get; set; }
        public int YearID { get; set; }
        public Nullable<byte> PositionID { get; set; }
        public Nullable<byte> Grade { get; set; }
        public Nullable<bool> ContractPermanent { get; set; }
        public string EvaluationGrade { get; set; }
        public string Remark { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<double> SalaryAllowance { get; set; }
        public Nullable<double> SalarySeniority { get; set; }
        public Nullable<System.Guid> RecordID { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
