//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHistory
    {
        public int EmployeeHistoryID { get; set; }
        public int EmployeeID { get; set; }
        public string HistoryDescription { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public string HistoryCategory { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public string BeforeDataChanged { get; set; }
        public string AfterDataChanged { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
