//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAreas
    {
        public string RoomID { get; set; }
        public string RoomDescription { get; set; }
        public byte Warehouse { get; set; }
        public Nullable<int> RoomArea { get; set; }
        public Nullable<int> QuantityOfPallets { get; set; }
        public Nullable<int> RoomVolume { get; set; }
        public Nullable<int> StoreID { get; set; }
        public int EmployeeAreaID { get; set; }
    }
}
