//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeKPIPosition
    {
        public int EmployeeKPIPositionID { get; set; }
        public int EmployeeKPIDefinitionID { get; set; }
        public int PositionID { get; set; }
        public string EmployeeKPIPositionRemark { get; set; }
    }
}
