//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeKPIDefinition
    {
        public int EmployeeKPIDefinitionID { get; set; }
        public string EmployeeKPIDescriptions { get; set; }
        public string EmployeeKPIType { get; set; }
        public int EmployeeKPICategoryID { get; set; }
        public Nullable<int> EmployeeKPIPoint { get; set; }
        public string EmployeeKPICalculationMethod { get; set; }
        public string EmployeeKPIProof { get; set; }
        public string EmployeeKPIUnitMeasurement { get; set; }
        public string EmployeeKPIRemark { get; set; }
        public string EmployeeKPINumber { get; set; }
        public string Object { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
