//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOTLeaveRemainDaytmp
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public bool ContractPermanent { get; set; }
        public bool Active { get; set; }
        public Nullable<int> LEA { get; set; }
        public int Workingyear { get; set; }
    }
}
