//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeKPITarget
    {
        public int EmployeeKPITargetID { get; set; }
        public int ReferenceID { get; set; }
        public int EmployeeKPIDefintionID { get; set; }
        public string TargetFrequency { get; set; }
        public string TargetMeasure { get; set; }
        public string TargetQty { get; set; }
        public double TargetWeight { get; set; }
        public decimal EmployeeKPITargetAmount { get; set; }
        public string EmployeeKPITargetRemark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string EmployeeKPITargetCategory { get; set; }
    }
}
