//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gate_Companies
    {
        public Gate_Companies()
        {
            this.Gate_Workers = new HashSet<Gate_Workers>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyNumber { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhoneNumber { get; set; }
        public string CompanyContact { get; set; }
        public string CustomerNumber { get; set; }
        public Nullable<int> StoreID { get; set; }
    
        public virtual ICollection<Gate_Workers> Gate_Workers { get; set; }
    }
}
