//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gate_EmployeeInOut
    {
        public int EmployeeInOutID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<bool> CheckOut { get; set; }
        public string Remark { get; set; }
        public string BikeNumber { get; set; }
        public Nullable<bool> CheckBike { get; set; }
        public Nullable<byte> Gate { get; set; }
        public bool Lunch { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public byte[] TS { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
