//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gate_Workers
    {
        public Gate_Workers()
        {
            this.Gate_WorkerLaborSafetyTraining = new HashSet<Gate_WorkerLaborSafetyTraining>();
            this.Gate_WorkerRegularInOut = new HashSet<Gate_WorkerRegularInOut>();
        }
    
        public int WorkerID { get; set; }
        public string WorkerName { get; set; }
        public int CompanyID { get; set; }
        public string CardID { get; set; }
        public string Comment { get; set; }
        public string Category { get; set; }
        public string CardType { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual Gate_Companies Gate_Companies { get; set; }
        public virtual ICollection<Gate_WorkerLaborSafetyTraining> Gate_WorkerLaborSafetyTraining { get; set; }
        public virtual ICollection<Gate_WorkerRegularInOut> Gate_WorkerRegularInOut { get; set; }
    }
}
