//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gate_PropertyMovements
    {
        public int PropertyMovementID { get; set; }
        public Nullable<System.DateTime> PropertyMovementDate { get; set; }
        public int PropertyID { get; set; }
        public string AuthorizedBy { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public byte Gate { get; set; }
        public string Remark { get; set; }
        public string CustomerName { get; set; }
        public double Quantity { get; set; }
    }
}
