//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalAuditEmployees
    {
        public int InternalAuditEmployeeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> InternalAuditID { get; set; }
        public string DisciplineActionReference { get; set; }
        public string DisciplineAction { get; set; }
        public Nullable<int> RemainderID { get; set; }
        public string ActionDescriptions { get; set; }
        public Nullable<byte> ActionType { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<byte> StatusProcess { get; set; }
        public Nullable<int> AttachmentID { get; set; }
    }
}
