//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalAudits
    {
        public int InternalAuditID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> ResolvedEmployeeID { get; set; }
        public string PreventativeAction { get; set; }
        public string CorrectiveResult { get; set; }
        public Nullable<System.DateTime> InternalAuditDate { get; set; }
        public Nullable<bool> InternalAuditConfirmed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> PreventativeActionDoneTime { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public string ManagerFeedback { get; set; }
        public byte[] TS { get; set; }
        public string CorrectiveAction { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> InternalAuditStatus { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> CorrectiveActionDoneTime { get; set; }
        public Nullable<bool> PreventativeActionStatus { get; set; }
        public Nullable<bool> PreventativeActionRequired { get; set; }
        public string DocumentFolder { get; set; }
        public string PreventativeActionBy { get; set; }
        public Nullable<bool> Complained { get; set; }
        public Nullable<System.DateTime> CompleteBeforeDate { get; set; }
        public int ProblemCategoryID { get; set; }
        public Nullable<int> ProductDamageID { get; set; }
        public string Location { get; set; }
        public bool Hospitalized { get; set; }
        public bool MedicalTreated { get; set; }
        public bool Injured { get; set; }
        public string CorrectiveActionBy { get; set; }
        public Nullable<System.DateTime> CorrectiveBeforeDate { get; set; }
        public Nullable<int> AccidentID { get; set; }
        public Nullable<int> Weight { get; set; }
        public string ProblemNumber { get; set; }
        public string RootCause { get; set; }
        public Nullable<byte> Severity { get; set; }
        public Nullable<byte> Likehood { get; set; }
        public string AccidentLevel { get; set; }
        public Nullable<byte> ComplainedLevel { get; set; }
        public Nullable<int> StoreID { get; set; }
    }
}
