//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIDefinitions
    {
        public int KPIDefinitionID { get; set; }
        public string KPIDefinitionDescription { get; set; }
        public string KPICategory { get; set; }
        public Nullable<float> KPIScoreStandard { get; set; }
        public string KPIRemark { get; set; }
    }
}
