//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIRecordings
    {
        public int KPIID { get; set; }
        public string KPIDescription { get; set; }
        public Nullable<float> KPIScore123Day { get; set; }
        public string KPIComment { get; set; }
        public Nullable<int> PayRollMonthID { get; set; }
        public Nullable<int> KPIDefinitionID { get; set; }
        public Nullable<float> KPIScore45Day { get; set; }
        public Nullable<float> KPIScore12345Afternoon { get; set; }
        public Nullable<float> KPIScoreShift3 { get; set; }
        public Nullable<bool> KPIConfirmed { get; set; }
        public byte[] ts { get; set; }
    }
}
