//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingReportDetail
    {
        public int LoadingReportDetailID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> LoadingReportID { get; set; }
        public Nullable<int> D1 { get; set; }
        public Nullable<int> D2 { get; set; }
        public Nullable<int> D3 { get; set; }
        public Nullable<int> D4 { get; set; }
        public Nullable<int> D5 { get; set; }
        public Nullable<int> D6 { get; set; }
        public Nullable<int> D7 { get; set; }
        public Nullable<int> D8 { get; set; }
        public Nullable<int> D9 { get; set; }
        public Nullable<int> D10 { get; set; }
        public Nullable<int> D11 { get; set; }
        public Nullable<int> D12 { get; set; }
        public Nullable<int> D13 { get; set; }
        public Nullable<int> D14 { get; set; }
        public Nullable<int> D15 { get; set; }
        public Nullable<int> D16 { get; set; }
        public Nullable<int> D17 { get; set; }
        public Nullable<int> D18 { get; set; }
        public Nullable<int> D19 { get; set; }
        public Nullable<int> D20 { get; set; }
        public Nullable<int> D21 { get; set; }
        public Nullable<int> D22 { get; set; }
        public Nullable<int> D23 { get; set; }
        public Nullable<int> D24 { get; set; }
        public Nullable<int> D25 { get; set; }
        public Nullable<int> D26 { get; set; }
        public Nullable<int> D27 { get; set; }
        public Nullable<int> D28 { get; set; }
        public Nullable<int> D29 { get; set; }
        public Nullable<int> D30 { get; set; }
        public Nullable<int> D31 { get; set; }
        public Nullable<int> D32 { get; set; }
        public Nullable<int> D33 { get; set; }
        public Nullable<int> D34 { get; set; }
        public Nullable<int> D35 { get; set; }
        public Nullable<int> D36 { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public byte[] TS { get; set; }
        public Nullable<int> Sorting { get; set; }
        public Nullable<int> ProductQuantityCheck { get; set; }
        public string Remark { get; set; }
        public Nullable<int> D37 { get; set; }
        public Nullable<int> D38 { get; set; }
        public Nullable<int> D39 { get; set; }
        public Nullable<int> D40 { get; set; }
        public Nullable<int> D41 { get; set; }
        public Nullable<int> D42 { get; set; }
        public Nullable<int> D43 { get; set; }
        public Nullable<int> D44 { get; set; }
        public Nullable<int> D45 { get; set; }
    }
}
