//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Locations
    {
        public Locations()
        {
            this.DispatchingLocations = new HashSet<DispatchingLocations>();
        }

        public int LocationID { get; set; }
        public string LocationNumber { get; set; }
        public string RoomID { get; set; }
        public short Aisle { get; set; }
        public short Bay { get; set; }
        public short High { get; set; }
        public short Deep { get; set; }
        public short Used { get; set; }
        public string Remark { get; set; }
        public bool Top { get; set; }
        public bool Low { get; set; }
        public string LocationNumberShort { get; set; }
        public Nullable<byte> isBusy { get; set; }
        public Nullable<long> ProductQuantity { get; set; }
        public Nullable<int> PalletQuantity { get; set; }
        public byte LocationCode { get; set; }
        public bool VeryLowHigh { get; set; }
        public Nullable<decimal> MaxWeight { get; set; }
        public Nullable<int> StoreID { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<DispatchingLocations> DispatchingLocations { get; set; }
        public virtual Rooms Rooms { get; set; }

        public string UsedEx
        {
            get
            {
                if (this.Used.Equals(1))
                    return "Yes";
                else
                    return "No";
            }
        }
    }
}
