//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;

    public partial class LocationsHome
    {
        public int LocationID { get; set; }
        public string LocationNum { get; set; }
        public short Bay { get; set; }
        public string RoomID { get; set; }
        public short High { get; set; }
        public short Deep { get; set; }
        public int StoreID { get; set; }
    }
}
