//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHLWorkDetails
    {
        public int MHLWorkDetailID { get; set; }
        public int MHLWorkID { get; set; }
        public int EmployeeID { get; set; }
        public float Quantity { get; set; }
        public string DetailRemark { get; set; }
        public bool CheckDelete { get; set; }
        public byte[] ts { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual MHLWorks MHLWorks { get; set; }
    }
}
