//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHLWorkDefinitions
    {
        public MHLWorkDefinitions()
        {
            this.MHLWorks = new HashSet<MHLWorks>();
        }
    
        public int MHLWorkDefinitionID { get; set; }
        public string JobName { get; set; }
        public string Description { get; set; }
        public Nullable<float> UnitPrice { get; set; }
        public string Unit { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> CustomerMainID { get; set; }
        public string MHLWorkDefinitionNumber { get; set; }
        public string MHLWorkDefinitionRemark { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual ICollection<MHLWorks> MHLWorks { get; set; }
    }
}
