//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MHLWorks
    {
        public MHLWorks()
        {
            this.MHLWorkDetails = new HashSet<MHLWorkDetails>();
        }
    
        public int MHLWorkID { get; set; }
        public Nullable<int> PayRollMonthID { get; set; }
        public System.DateTime MHLWorkDate { get; set; }
        public string CreatedBy { get; set; }
        public int Received { get; set; }
        public int Damaged { get; set; }
        public bool MHLWorkConfirm { get; set; }
        public string Remark { get; set; }
        public int MHLWorkDefinitionID { get; set; }
        public Nullable<float> UnitPrice { get; set; }
        public Nullable<int> OtherServiceDetailID { get; set; }
        public Nullable<int> CustomerMainID { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public bool Accepted { get; set; }
        public string AcceptedBy { get; set; }
        public bool Rejected { get; set; }
        public string RejectedBy { get; set; }
        public string ManagerFeedback { get; set; }
        public string WorkNumber { get; set; }
        public byte[] ts { get; set; }
        public string OrderNumber { get; set; }

        public virtual MHLWorkDefinitions MHLWorkDefinitions { get; set; }
        public virtual ICollection<MHLWorkDetails> MHLWorkDetails { get; set; }
        public virtual PayrollMonth PayrollMonth { get; set; }
    }
}
