//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPayRollSummary
    {
        public int PayRollMonthID { get; set; }
        public string PayRollMonth { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<float> WorkingDays { get; set; }
        public Nullable<float> WorkingDaysChange { get; set; }
        public Nullable<float> PayableHolidays { get; set; }
        public Nullable<float> OTS { get; set; }
        public Nullable<float> OTSChange { get; set; }
        public Nullable<float> OTN { get; set; }
        public Nullable<float> OTNChange { get; set; }
        public Nullable<float> TotalWorkerHour { get; set; }
        public Nullable<float> TotalWorkerHourSCS { get; set; }
        public Nullable<float> TotalWorkerHourChange { get; set; }
        public Nullable<float> Accidents { get; set; }
        public Nullable<float> AccidentsChange { get; set; }
        public Nullable<float> AccidentLeave { get; set; }
        public Nullable<float> AccidentLeaveChange { get; set; }
        public Nullable<float> SickLeave { get; set; }
        public Nullable<float> SickLeavechange { get; set; }
        public Nullable<int> LeaveMoreThan3Days { get; set; }
        public Nullable<float> LeaveMoreThan3DayChange { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> EmployeePermanentQty { get; set; }
        public Nullable<int> EmployeeTemporaryQty { get; set; }
        public Nullable<float> OTH { get; set; }
        public Nullable<float> OTHChange { get; set; }
        public Nullable<float> HalfSum { get; set; }
        public Nullable<float> OffSum { get; set; }
        public Nullable<float> LeaveSum { get; set; }
        public byte[] ts { get; set; }
    }
}
