//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int NoteID { get; set; }
        public System.DateTime NoteDate { get; set; }
        public int CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string NoteDescription { get; set; }
        public string DocumentFolder { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string VehicleNumber { get; set; }
        public string CustomerRefNumber { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public bool Confirmed { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> OccurTime { get; set; }
        public string CustomerRepresentative { get; set; }
        public string RepresentativePosition { get; set; }
        public string OccurLocation { get; set; }
        public Nullable<int> SupervisorID { get; set; }
    }
}
