//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingCostDefinitions
    {
        public OperatingCostDefinitions()
        {
            this.OperatingCostMonthlyDetails = new HashSet<OperatingCostMonthlyDetails>();
        }
    
        public int OperatingCostID { get; set; }
        public string OperatingCostDescription { get; set; }
        public string OperatingCostCode { get; set; }
        public string OperatingCostRemark { get; set; }
        public string CalculationMethod { get; set; }
        public string CalculationSQL { get; set; }
        public bool AutoCalculation { get; set; }
    
        public virtual ICollection<OperatingCostMonthlyDetails> OperatingCostMonthlyDetails { get; set; }
    }
}
