//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingCostLabourDetails
    {
        public int OperatingCostLabourDetailID { get; set; }
        public int OperatingCostLabourID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<decimal> Productivity { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public Nullable<decimal> LabourCostAmount { get; set; }
        public Nullable<decimal> DriverRate { get; set; }
        public string LabourType { get; set; }
        public Nullable<decimal> LabourCostAmountAdjusted { get; set; }
        public Nullable<decimal> LabourCostAmountAdjustRated { get; set; }
    
        public virtual OperatingCostLabours OperatingCostLabours { get; set; }
    }
}
