//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingCostMonthlyDetails
    {
        public OperatingCostMonthlyDetails()
        {
            this.OperatingCostDetailByCustomers = new HashSet<OperatingCostDetailByCustomers>();
        }
    
        public int OperatingCostMonthlyDetailID { get; set; }
        public int OperatingCostMonthlyID { get; set; }
        public int OperatingCostID { get; set; }
        public decimal OperatingCostQuantity { get; set; }
        public string OperatingCostMonthlyDetailRemark { get; set; }
        public Nullable<byte> StoreID { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }

        public virtual OperatingCostDefinitions OperatingCostDefinitions { get; set; }
        public virtual ICollection<OperatingCostDetailByCustomers> OperatingCostDetailByCustomers { get; set; }
        public virtual OperatingCostMonths OperatingCostMonths { get; set; }



    }
}
