//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingCostLabours
    {
        public OperatingCostLabours()
        {
            this.OperatingCostLabourDetails = new HashSet<OperatingCostLabourDetails>();
        }
    
        public int OperatingCostLabourID { get; set; }
        public int OperatingCostMonthlyID { get; set; }
        public int EmployeeID { get; set; }
        public decimal LabourCostAmount { get; set; }
        public string LabourCostRemark { get; set; }
    
        public virtual ICollection<OperatingCostLabourDetails> OperatingCostLabourDetails { get; set; }
        public virtual OperatingCostMonths OperatingCostMonths { get; set; }
    }
}
