//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingCostDetailByCustomers
    {
        public int OperatingCostDetailByCustomerID { get; set; }
        public int CustomerID { get; set; }
        public int OperatingCostMonthlyDetailID { get; set; }
        public decimal OperatingCostDetailByCustomerQuantity { get; set; }
        public string OperatingCostDetailByCustomerRemark { get; set; }
        public decimal OperatingCostDriverRate { get; set; }
        public Nullable<decimal> OperatingCostDetailByCustomerQuantityAdjusted { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual OperatingCostMonthlyDetails OperatingCostMonthlyDetails { get; set; }
    }
}
