//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperatingCostNonlistedRates
    {
        public int NominalRateID { get; set; }
        public string TaskDescription { get; set; }
        public decimal NominalRate { get; set; }
        public string TaskRemark { get; set; }
    }
}
