//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationCostBlastFreezing
    {
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> BlastFreezerCreateTime { get; set; }
        public Nullable<System.DateTime> StartLoadingTime { get; set; }
        public Nullable<System.DateTime> EndLoadingTime { get; set; }
        public Nullable<System.DateTime> BlastFreezerUloadingTime { get; set; }
        public int BlastFreezerRoomID { get; set; }
        public System.DateTime DateIn { get; set; }
        public string UserName { get; set; }
        public string ProductDetailsRemark { get; set; }
        public string BlastFreezerLoadingBy { get; set; }
        public Nullable<System.DateTime> StartRunTime { get; set; }
        public Nullable<System.DateTime> EndRunTime { get; set; }
        public string BlastFreezerRunningRemark { get; set; }
        public string BlastFreezerRecordNumber { get; set; }
    }
}
