//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    
    public partial class OtherService
    {
        public OtherService()
        {
            this.OtherServiceDetails = new HashSet<OtherServiceDetails>();
        }
    
        public int OtherServiceID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public string ServiceRemark { get; set; }
        public string CustomerRep { get; set; }
        public bool LockStatus { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> BillingID { get; set; }
        public Nullable<bool> MHLBillingConfirm { get; set; }
        public byte[] ts { get; set; }
        public Nullable<System.DateTime> MHLBillingDate { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<byte> Status { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public bool isBillingAdjustment { get; set; }
        public virtual Customers Customers { get; set; }
         [XmlIgnoreAttribute]
        public virtual ICollection<OtherServiceDetails> OtherServiceDetails { get; set; }
    }
}
