//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherJobs
    {
        public int OtherJobID { get; set; }
        public string OtherJobNumber { get; set; }
        public System.DateTime OtherJobDate { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public float WorkingHour { get; set; }
        public int JobDefinitionID { get; set; }
        public string JobDescriptionDetails { get; set; }
        public bool Confirmed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public string ReferenceID { get; set; }
        public string JobDefinitionNameVietnam { get; set; }
        public bool Accepted { get; set; }
        public byte[] ts { get; set; }
        public Nullable<System.DateTime> AcceptedTime { get; set; }
        public string JobStatus { get; set; }
        public string Feedback { get; set; }
        public string SupervisorSpecialRequirement { get; set; }
        public string ManagerFeedback { get; set; }
        public string ConfirmedBy { get; set; }
        public string AcceptedBy { get; set; }
        public string PersonnelFeedback { get; set; }
        public bool Reject { get; set; }
    }
}
