//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherJobDefinitions
    {
        public int JobDefinitionID { get; set; }
        public string JobDefinitionCode { get; set; }
        public string JobDefinitionName { get; set; }
        public string JobDefinitionNameVietnam { get; set; }
        public string Remark { get; set; }
    }
}
