//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalletHoldings
    {
        public int PalletHoldingID { get; set; }
        public string PalletHoldingBy { get; set; }
        public string PalletHoldingDescription { get; set; }
        public System.DateTime PalletHoldingTime { get; set; }
        public bool OnHold { get; set; }
        public int PalletID { get; set; }
        public Nullable<byte> PalletStatus { get; set; }
    }
}
