//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;

    public partial class PalletCartons
    {
        public int PalletCartonID { get; set; }
        public int PalletID { get; set; }
        public Nullable<float> PalletWeight { get; set; }
        public string PalletRemark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public byte[] ts { get; set; }
        public Nullable<decimal> PalletGrossWeight { get; set; }
        public Nullable<int> CartonUnits { get; set; }
        public Nullable<bool> CheckDelete { get; set; }
        public Nullable<decimal> CartonWeightPay { get; set; }
        public Nullable<float> NetWeightSupplier { get; set; }
        public string CartonManufacturingBarcode { get; set; }
        public string ProductTypeMP { get; set; }
        public string ProductCodeMP { get; set; }
        public string ProductNameMP { get; set; }
        public string SizeMP { get; set; }
        public string BatchMP { get; set; }
        public string TraceCodeMP { get; set; }
        public Nullable<decimal> QtyMP { get; set; }
        public string UnitMP { get; set; }
        public string POCodeMP { get; set; }
        public string ProDateMP { get; set; }
        public string ExpDateMP { get; set; }
        public string FactoryCodeMP { get; set; }
        public string IDCartonMP { get; set; }
        public string SOMP { get; set; }
        public string T15MP { get; set; }
        public bool IsModified { get; set; }
    }
}
