//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;

    public partial class PalletCartons
    {
        public int PalletCartonID { get; set; }
        public int PalletID { get; set; }
        public Nullable<float> PalletWeight { get; set; }
        public string PalletRemark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
        public byte[] ts { get; set; }
        public Nullable<decimal> PalletGrossWeight { get; set; }
        public Nullable<int> CartonUnits { get; set; }
        public Nullable<bool> CheckDelete { get; set; }
        public Nullable<decimal> CartonWeightPay { get; set; }
        public Nullable<float> NetWeightSupplier { get; set; }
        public Nullable<decimal> TareWeight { get; set; }
        public string Size { get; set; }
        public string Batch { get; set; }
        public string TraceCode { get; set; }
        public string POCode { get; set; }
        public string DateOfYear { get; set; }
        public int NoBatch{ get; set; }
        public bool IsModified { get; set; }
    }
}
