//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollMonthlyDetails
    {
        public int PayRollMonthlyID { get; set; }
        public Nullable<int> PayRollMonthID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<bool> ContractPermanent { get; set; }
        public Nullable<float> WorkingDays { get; set; }
        public Nullable<float> WorkingDayNightShift { get; set; }
        public Nullable<float> OTS { get; set; }
        public Nullable<float> OTN { get; set; }
        public Nullable<float> OTH { get; set; }
        public Nullable<float> Sick { get; set; }
        public Nullable<float> Leave { get; set; }
        public Nullable<float> Haft { get; set; }
        public Nullable<float> Off { get; set; }
        public string User { get; set; }
        public string ABC { get; set; }
        public float Performance { get; set; }
        public float PerformanceAverage { get; set; }
        public Nullable<float> PerformancePercent { get; set; }
        public bool PerformanceStatus { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string Position { get; set; }
        public Nullable<byte> DepartmentID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public string PayRollMonthlyRemark { get; set; }
        public Nullable<bool> Advance { get; set; }
        public Nullable<bool> Active { get; set; }
        public string SupervisorRemark { get; set; }
        public string SupervisorUser { get; set; }
        public Nullable<bool> PersonnelCheck { get; set; }
        public string PersonnelRemark { get; set; }
        public Nullable<System.DateTime> PersonnelCheckTime { get; set; }
        public Nullable<bool> SafetyCheck { get; set; }
        public string SafetyRemark { get; set; }
        public Nullable<System.DateTime> SafetyCheckTime { get; set; }
        public Nullable<bool> ManagerCheck { get; set; }
        public string ManagerRemark { get; set; }
        public string ManagerCheckUser { get; set; }
        public string ABCtemp { get; set; }
        public byte[] TS { get; set; }
        public bool IsBirthday { get; set; }
        public string EvaluationSafety { get; set; }
        public string EvaluationPerformance { get; set; }
        public string EvaluationTime { get; set; }
        public string EvaluationAttitude { get; set; }
        public Nullable<float> WorkingDayHoliday { get; set; }
        public Nullable<float> OTH_ { get; set; }
        public Nullable<bool> AllowUpdated { get; set; }
        public Nullable<float> OTNN { get; set; }
        public Nullable<float> OTSN { get; set; }
        public Nullable<float> OTHN { get; set; }
        public Nullable<float> OTNN_ { get; set; }
        public string ABC1 { get; set; }
        public string EvaluationCreative { get; set; }
        public string PersonnelUser { get; set; }
    }
}
