//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollMonth
    {
        public PayrollMonth()
        {
            this.MHLWorks = new HashSet<MHLWorks>();
        }
    
        public int PayRollMonthID { get; set; }
        public string PayRollMonth1 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> WorkingDays { get; set; }
        public Nullable<int> SundayHoliday { get; set; }
        public Nullable<int> PayableHoliday { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public bool PayrollMonthConfirm { get; set; }
        public bool PayrollMonthLock { get; set; }
        public string AcceptBy { get; set; }
        public string AccountingUser { get; set; }
        public byte[] ts { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> AccountingTime { get; set; }
        public Nullable<bool> NSMHL { get; set; }
        public Nullable<bool> AccountingConfirm { get; set; }
    
        public virtual ICollection<MHLWorks> MHLWorks { get; set; }
    }
}
