//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Positions
    {
        public Positions()
        {
            this.Employees = new HashSet<Employees>();
        }

        public int PositionID { get; set; }
        public string PositionDescription { get; set; }
        public string PositionVietnam { get; set; }
        public Nullable<byte> ManagementLevel { get; set; }
        public bool isProductivity { get; set; }
        public string CustomerAllocationMethod { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ReportToPositionID { get; set; }
        public bool isDirectLabour { get; set; }
        public Nullable<bool> Active { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
