//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;

    public partial class Products
    {
        public int ProductID { get; set; }
        public string ProductNumber { get; set; }
        public string SubCode { get; set; }
        public string ProductNumberEx
        {
            get
            {
                string exNumber = this.ProductNumber;
                if (this.ProductNumber.Length >= 4)
                {
                    exNumber = this.ProductNumber.Substring(4);
                }
                return exNumber;
            }
        }
        public int CustomerID { get; set; }
        public string ProductName { get; set; }
        public decimal WeightPerPackage { get; set; }
        public short Pcs { get; set; }
        public Nullable<float> TemperatureRequire { get; set; }
        public short PackagesPerPallet { get; set; }
        public Nullable<short> PackagesPerPallet2 { get; set; }
        public string ManufacturerBarcode { get; set; }
        public string Remark { get; set; }
        public string Packages { get; set; }
        public int HomeLocation1 { get; set; }
        public int HomeLocation2 { get; set; }
        public Nullable<int> PickingLocation { get; set; }
        public Nullable<short> Inners { get; set; }
        public string ERPUnit { get; set; }
        public Nullable<bool> Discontinue { get; set; }
        public string HomeRoom1 { get; set; }
        public string HomeRoom2 { get; set; }
        public bool PickingMethod { get; set; }
        public int ProductCategory { get; set; }
        public byte[] TS { get; set; }
        public Nullable<int> WAREHOUSE_NO { get; set; }
        public Nullable<decimal> GrossWeightPerPackage { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public string ProductNameVN { get; set; }
        public Nullable<byte> ProductCategoryID { get; set; }
        public Nullable<short> WarningDaysBeforeExpiry { get; set; }
        public Nullable<bool> IsWeightingRequire { get; set; }
        public Nullable<bool> IsAllowLocationChange { get; set; }
        public string Origin { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<int> ProductMainID { get; set; }
        public Nullable<int> SafetyStock { get; set; }
        public Nullable<System.DateTime> WarningSilenceDate { get; set; }
        public string GTIN { get; set; }
        public Nullable<int> SelfLifeDays { get; set; }
        public Nullable<int> QuyCach { get; set; }
        public Nullable<bool> HasSyncNavi { get; set; }
        public string SizeBox { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<bool> IsNet { get; set; }
    }
}
