//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTransformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTransformation()
        {
            this.ProductTransRecordDetails = new HashSet<ProductTransRecordDetail>();
        }
    
        public int ProductTransformationID { get; set; }
        public int CustomerID { get; set; }
        public string TransformationFormula { get; set; }
        public string ProductTransformationRemark { get; set; }
        public int SourceProduct1ID { get; set; }
        public Nullable<int> SourceProduct2ID { get; set; }
        public Nullable<int> SourceProduct3ID { get; set; }
        public Nullable<int> TransformationType { get; set; }
        public int FinishProduct1ID { get; set; }
        public Nullable<int> FinishProduct2ID { get; set; }
        public Nullable<int> FinishProduct3ID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int SourceProduct1Qty { get; set; }
        public Nullable<int> SourceProduct2Qty { get; set; }
        public Nullable<int> SourceProduct3Qty { get; set; }
        public int FinishProduct1Qty { get; set; }
        public Nullable<int> FinishProduct2Qty { get; set; }
        public Nullable<int> FinishProduct3Qty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTransRecordDetail> ProductTransRecordDetails { get; set; }
    }
}
