//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTransRecordDetail
    {
        public int ProductTransRecordDetailID { get; set; }
        public int ProductTransRecordID { get; set; }
        public int ProductTransformationID { get; set; }
        public int TransformationQuantity { get; set; }
        public string ProductTransDetailRemark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual ProductTransformation ProductTransformation { get; set; }
        public virtual ProductTransRecord ProductTransRecord { get; set; }
    }
}
