//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product824
    {
        public int ProductID { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public int CustomerID { get; set; }
        public decimal WeightPerPackage { get; set; }
        public Nullable<short> Inners { get; set; }
        public string Packages { get; set; }
        public string Remark { get; set; }
        public short PackagesPerPallet { get; set; }
        public int HomeLocation1 { get; set; }
        public int HomeLocation2 { get; set; }
        public string HomeRoom1 { get; set; }
        public string HomeRoom2 { get; set; }
        public bool PickingMethod { get; set; }
        public int ProductCategory { get; set; }
        public Nullable<float> TemperatureRequire { get; set; }
    }
}
