//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_HN
    {
        public string ProductNumberMISA { get; set; }
        public string ProductNameMISA { get; set; }
        public string ProductNumberSAP { get; set; }
        public string ProductNameSAP { get; set; }
        public string Packages { get; set; }
        public Nullable<int> Store { get; set; }
        public int ID { get; set; }
    }
}
