//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPackage
    {
        public int ProductPackageID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Levels { get; set; }
        public string ERP { get; set; }
        public string UOM { get; set; }
        public Nullable<int> HS { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
