//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDamages
    {
        public int ProductDamageID { get; set; }
        public Nullable<System.DateTime> DamageDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CustomerName { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public string Quantity { get; set; }
        public string DamageDescription { get; set; }
        public string Location { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> EstimatedValueLost { get; set; }
        public string CurrencyUnit { get; set; }
        public string ProposedSolution { get; set; }
        public string ActionTakenBy { get; set; }
        public Nullable<System.DateTime> ActionDate_bo { get; set; }
        public string CustomerRepresentative { get; set; }
        public string CustomerFeedback { get; set; }
        public string DamageConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public string ManagerFeedback { get; set; }
        public bool DamageConfirmed { get; set; }
        public string ExpensesCoverBy { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string DocumentFolder { get; set; }
        public byte[] TS { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CorrectiveAction { get; set; }
        public string CorrectiveResult { get; set; }
        public Nullable<int> CorrectiveEmployeeID { get; set; }
        public Nullable<bool> CorrectiveDone { get; set; }
        public Nullable<System.DateTime> CorrectiveActionDoneTime { get; set; }
        public Nullable<bool> PreventativeActionRequired { get; set; }
        public string PreventativeAction { get; set; }
        public string PreventativeActionBy { get; set; }
        public Nullable<bool> PreventativeActionStatus { get; set; }
        public Nullable<System.DateTime> PreventativeActionDoneTime { get; set; }
        public Nullable<System.DateTime> CompleteBeforeDate { get; set; }
        public Nullable<int> ProblemCategoryID { get; set; }
    }
}
