//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiles
    {
        public int MyProfileID { get; set; }
        public int EmployeeID { get; set; }
        public int CustomerMainID { get; set; }
        public bool DefaultCustomer { get; set; }
    }
}
