//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public string PartOriginal { get; set; }
        public string PartNumber { get; set; }
        public int PartGroupID { get; set; }
        public int PartCategoryID { get; set; }
        public string EquipmentGroupID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string PartRemark { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string PropertyModelAndSpecification { get; set; }
        public string Unit { get; set; }
        public Nullable<float> UnitPriceVND { get; set; }
        public Nullable<float> UnitPriceUSD { get; set; }
        public Nullable<System.DateTime> PartEntryTime { get; set; }
        public string PartOwner { get; set; }
        public string ITEquipmentSpecification { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> ITEquipmentBuyingDate { get; set; }
        public string CreatedBy { get; set; }
        public string PartOriginalType { get; set; }
        public Nullable<int> PropertyOldID { get; set; }
    }
}
