//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class QHSE_Equipments
    {
        public int QHSE_EquipmentID { get; set; }
        public string QHSE_EquipmentNumber { get; set; }
        public int StoreID { get; set; }
        public int DepartmentID { get; set; }
        public int QHSE_EquipmentCategoryID { get; set; }
        public string EquipmentName { get; set; }
        public string SerialNumnber { get; set; }
        public string Model { get; set; }
        public string Specifications { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> GuaranteeDate { get; set; }
        public Nullable<System.DateTime> CalibratingDate { get; set; }
        public string CalibrationDocumentNumber { get; set; }
        public Nullable<System.DateTime> NextCalibrationDate { get; set; }
        public Nullable<int> RequiredCalibrationDays { get; set; }
        public string QHSE_EquipmentRemark { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool Confirmed { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public Nullable<bool> IsAttachment { get; set; }
    }
}
