//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class QHSE
    {
        public int QHSEID { get; set; }
        public string QHSENumber { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public string Category { get; set; }
        public Nullable<bool> PhotoAttachment { get; set; }
        public string Comment { get; set; }
        public string ManagementResponse { get; set; }
        public string ResponseBy { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public string Location { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public string AssignedComment { get; set; }
        public bool Confirmed { get; set; }
        public byte[] ts { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> AssignedCommentTime { get; set; }
        public System.DateTime Deadline { get; set; }
        public Nullable<int> Department { get; set; }
        public bool AssigmentReject { get; set; }
        public Nullable<byte> TaskProgress { get; set; }
        public Nullable<decimal> Evaluation { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
    }
}
