//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityCheckings
    {
        public QualityCheckings()
        {
            this.QualityCheckingDetails = new HashSet<QualityCheckingDetails>();
        }
    
        public int QualityCheckingID { get; set; }
        public System.DateTime QualityCheckingDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string CreatedBy { get; set; }
        public bool Confirmed { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedTime { get; set; }
        public string QualityCheckingRemark { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    
        public virtual ICollection<QualityCheckingDetails> QualityCheckingDetails { get; set; }
    }
}
