//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarantineDetails
    {
        public int QuarantineDetailID { get; set; }
        public int QuarantineID { get; set; }
        public int ReceivingOrderDetailID { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public int TotalPackages { get; set; }
        public float WeightPerPackage { get; set; }
        public string QuarantineDetailRemark { get; set; }
        public int ProductID { get; set; }
        public string ICUser { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
