//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class ReceivingOrders
    {
        public ReceivingOrders()
        {
            this.ReceivingOrderDetails = new HashSet<ReceivingOrderDetails>();
        }

        public int ReceivingOrderID { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public int CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public bool Status { get; set; }
        public Nullable<float> Temperature { get; set; }
        public string SpecialRequirement { get; set; }
        public Nullable<System.DateTime> ReceivingCreatedTime { get; set; }
        public string Owner { get; set; }
        public string DockNumber { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<byte> ReceivingOrderProgress { get; set; }
        public string SealNumber { get; set; }
        public byte[] TS { get; set; }
        public string BLNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string LadingReportNumber { get; set; }
        public string CustomsDeclarationNumber { get; set; }
        public string ContractNumber { get; set; }
        public string Origin { get; set; }
        public Nullable<short> HandlingOvertimeCategoryID { get; set; }
        public string InternalRemark { get; set; }
        public Nullable<bool> Electricity { get; set; }
        public Nullable<double> ProgressPercentage { get; set; }
        public Nullable<int> CustomerSupplierID { get; set; }
        public Nullable<bool> IsAttachment { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> TimeSlotID { get; set; }
        public Nullable<int> DockDoorID { get; set; }
        public Nullable<double> PutAwayPercentage { get; set; }
        public Nullable<byte> ProcessingStatus { get; set; }
        public string CustomerOrderNumber2 { get; set; }

        public Nullable<System.DateTime> EDIMessageSentTime { get; set; }
        public Nullable<int> WorkTypeCode { get; set; }
        public virtual Customers Customers { get; set; }

        [XmlIgnoreAttribute]
        public virtual ICollection<ReceivingOrderDetails> ReceivingOrderDetails { get; set; }
    }
}
