//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingUnits
    {
        public int ReceivingUnitID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public int PalletCartonID { get; set; }
        public Nullable<decimal> UnitWeights { get; set; }
        public string CustomerRef { get; set; }
        public byte[] TS { get; set; }
    }
}
