//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportToCustomer
    {
        public int ReportToCustomerID { get; set; }
        public string SendObject { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime SentTime { get; set; }
        public string SentBy { get; set; }
        public string SendAddress { get; set; }
    }
}
