//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDates
    {
        public System.DateTime ReportDate { get; set; }
        public string ReportMonth { get; set; }
        public System.DateTime BeginOfTheMonth { get; set; }
        public System.DateTime EndOfTheMonth { get; set; }
        public int DaysOfTheMonth { get; set; }
        public int WeekNumber { get; set; }
        public Nullable<int> StockOnHandWeeklyID { get; set; }
    }
}
