//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Rooms
    {
        public Rooms()
        {
            this.Aisles = new HashSet<Aisles>();
            this.Locations = new HashSet<Locations>();
        }

        public string RoomID { get; set; }
        public float Temperature { get; set; }
        public Nullable<System.DateTime> DateRoom { get; set; }
        public byte Warehouse { get; set; }
        public string RoomDescription { get; set; }
        public Nullable<int> RoomArea { get; set; }
        public Nullable<int> QuantityOfPallets { get; set; }
        public Nullable<int> RoomVolume { get; set; }
        public string RoomProductStorage { get; set; }
        public Nullable<float> TemperatureFrom { get; set; }
        public Nullable<float> TemperatureTo { get; set; }
        public Nullable<float> HumidityFrom { get; set; }
        public Nullable<float> HumidityTo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> StoreID { get; set; }

        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> LostProductLocationID { get; set; }
        public bool isVirtual { get; set; }
        public bool isFullyLeased { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<Aisles> Aisles { get; set; }
        [XmlIgnoreAttribute]
        public virtual ICollection<Locations> Locations { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
