//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms_Locations
    {
        public string RoomID { get; set; }
        public int QtyLow { get; set; }
        public int QtyHigh { get; set; }
        public Nullable<int> QtyStandards { get; set; }
        public Nullable<int> QtyAvailable { get; set; }
        public string RoomRemark { get; set; }
    }
}
