//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafetyStocks
    {
        public int SafetyStockID { get; set; }
        public Nullable<int> ProductID6 { get; set; }
        public string ProductNumber6 { get; set; }
        public string ProductName6 { get; set; }
        public Nullable<int> SafetyStock { get; set; }
        public Nullable<int> ProductID2 { get; set; }
        public string Remark { get; set; }
        public string ProductNumber2 { get; set; }
        public string ProductName2 { get; set; }
        public Nullable<int> ProductIDPack { get; set; }
        public string ProductNumberP { get; set; }
        public string ProductNameP { get; set; }
    }
}
