//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesDefinition
    {
        public ServicesDefinition()
        {
            this.BillingDetails = new HashSet<BillingDetails>();
            this.ContractDetails = new HashSet<ContractDetails>();
            this.CustomerServiceCosting = new HashSet<CustomerServiceCosting>();
            this.OtherServiceDetails = new HashSet<OtherServiceDetails>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceNumber { get; set; }
        public string ServiceName { get; set; }
        public string Measure { get; set; }
        public string MeasureVietnam { get; set; }
        public bool Code { get; set; }
        public bool IsModified { get; set; }
        public Nullable<int> CustomerCategory { get; set; }
        public string ServiceCategory { get; set; }
        public Nullable<double> CheckingQuantityMax { get; set; }
        public Nullable<double> CheckingQuantityMin { get; set; }
        public string ServiceNameVietnamese { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<bool> HandlingOvertime { get; set; }
        public string ServiceType { get; set; }
        public string ServiceStandardScopeOfWork { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public string ScopeOfWork { get; set; }
        public string ScopeOFWorkVietnam { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public string CalculatedSQL { get; set; }
        public string HandlingOvertimeType { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string PLUServiceType { get; set; }
        public Nullable<decimal> Price { get; set; }

        public virtual ICollection<BillingDetails> BillingDetails { get; set; }
        public virtual ICollection<ContractDetails> ContractDetails { get; set; }
        public virtual ICollection<CustomerServiceCosting> CustomerServiceCosting { get; set; }
        public virtual ICollection<OtherServiceDetails> OtherServiceDetails { get; set; }
    }
}
