//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shifts
    {
        public Shifts()
        {
            this.DailyChecks = new HashSet<DailyChecks>();
        }
    
        public byte ShiftID { get; set; }
        public System.DateTime FromTime { get; set; }
        public System.DateTime ToTime { get; set; }
        public Nullable<byte> ShiftName { get; set; }

        public string ShiftValue
        {
           get
            {
               return this.FromTime.ToString("HH:mm") + "~" + this.ToTime.ToString("HH:mm");
            }
        }


        public virtual ICollection<DailyChecks> DailyChecks { get; set; }
    }
}
