//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLOMON_ServicesDefinition
    {
        public string serviceID { get; set; }
        public string ServiceName { get; set; }
        public string UOM { get; set; }
    }
}
