//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLOMON_ContractDetails
    {
        public string contractnbr { get; set; }
        public string CustomerID { get; set; }
        public string serviceID { get; set; }
        public System.DateTime Fromdate { get; set; }
        public System.DateTime ToDate { get; set; }
    }
}
