//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    
    public partial class STLabelPalletCartonWeight
    {
        public int CartonID { get; set; }
        public int Units { get; set; }
        public Nullable<Single> Net { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Gross { get; set; }
        public Nullable<decimal> Tare { get; set; }
        public Nullable<decimal> Weight { get; set; }
    }
}
