//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovements
    {
        public StockMovements()
        {
            this.StockMovementDetails = new HashSet<StockMovementDetails>();
        }
    
        public int StockMovementID { get; set; }
        public int SourceLocation { get; set; }
        public int DestinationLocation { get; set; }
        public Nullable<System.DateTime> DateMovement { get; set; }
        public bool Automatic { get; set; }
        public string ReasonMovement { get; set; }
        public string AuthorisedBy { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string StockMovementType { get; set; }
    
        public virtual ICollection<StockMovementDetails> StockMovementDetails { get; set; }
    }
}
