//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOnHandDailyDetails
    {
        public int StockOnHandDetailID { get; set; }
        public int DateID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ProductLines { get; set; }
        public Nullable<int> Pallets { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> Cartons { get; set; }
        public string Remarks { get; set; }
        public string DoneBy { get; set; }
        public Nullable<int> PalletLow { get; set; }
        public Nullable<int> PalletVeryLow { get; set; }
        public Nullable<int> PalletVeryHigh { get; set; }
        public Nullable<int> PalletHigh { get; set; }
    }
}
