//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovementDetails
    {
        public int StockMovementDetailID { get; set; }
        public Nullable<int> StockMovementID { get; set; }
        public Nullable<int> PalletID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual StockMovements StockMovements { get; set; }
    }
}
