//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOnHandDailyDetailPallets
    {
        public int StockOnHandDetailPalletID { get; set; }
        public int DateID { get; set; }
        public int PalletID { get; set; }
        public int ReceivingOrderDetailID { get; set; }
        public string Label { get; set; }
        public short OriginalQuantity { get; set; }
        public short AfterDPQuantity { get; set; }
        public short CurrentQuantity { get; set; }
        public bool OnHold { get; set; }
        public int LocationID { get; set; }
        public bool status { get; set; }
        public bool CanMove { get; set; }
        public string Remark { get; set; }
        public bool CanNotAdd { get; set; }
        public byte[] TS { get; set; }
        public Nullable<int> UnitQuantity { get; set; }
        public Nullable<float> PalletWeight { get; set; }
        public Nullable<byte> PalletStatus { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
