//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOnHandWeeklyDetails
    {
        public int DataID { get; set; }
        public int WeekID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ActualProductLines { get; set; }
        public Nullable<int> ConProductLines { get; set; }
        public Nullable<int> OccupiedPallets { get; set; }
        public Nullable<double> TotalWeight { get; set; }
        public Nullable<int> NumberOfCartons { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> HandlingWeight { get; set; }
        public Nullable<double> WorkerWeight { get; set; }
        public Nullable<double> DockHours { get; set; }
    }
}
