//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOnHandDailyDetailsByRoom
    {
        public int StockOnHandDailyByRoomID { get; set; }
        public int StockOnHandID { get; set; }
        public string RoomID { get; set; }
        public long QuantityPallets { get; set; }
        public long QuantityCartons { get; set; }
        public long QuantityWeight { get; set; }
        public int CustomerID { get; set; }
    }
}
