//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOnHandDailyInOut
    {
        public int StockOnHandDailyInOutID { get; set; }
        public int DateID { get; set; }
        public int InC { get; set; }
        public int InW { get; set; }
        public int InP { get; set; }
        public int OutC { get; set; }
        public int OutW { get; set; }
        public int OutP { get; set; }
    }
}
