//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stores
    {
        public int StoreID { get; set; }
        public string StoreNumber { get; set; }
        public string StoreDescription { get; set; }
        public string StoreVietnam { get; set; }
        public string RangeID { get; set; }
        public string Address { get; set; }
        public string CompanyName { get; set; }
        public string StoreNumberM3 { get; set; }
        public string E_Invoice_URL_Publish { get; set; }
        public string E_Invoice_URL_Portal { get; set; }
        public string E_Invoice_URL_Business { get; set; }
        public string E_Invoice_UserName { get; set; }
        public string E_Invoice_Password { get; set; }
        public string E_InvoiceCode { get; set; }
        public string TelFaxVAT { get; set; }
        public string TaxCode { get; set; }
        public string E_Invoice_AdminUser { get; set; }
        public string E_Invoice_AdminPassword { get; set; }
    }
}
