//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblagjenda
    {
        public int Id_Agjenda { get; set; }
        public string Titulli { get; set; }
        public string Useri { get; set; }
        public string data_takimit { get; set; }
        public string Kategoria { get; set; }
        public string data_e_publikimit { get; set; }
        public string e_kryer { get; set; }
        public string rezultati { get; set; }
    }
}
