//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int TestID { get; set; }
        public Nullable<System.DateTime> TestTime { get; set; }
        public string TestRemark { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductIDQty { get; set; }
        public Nullable<int> DispatchingOrderID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string UserName { get; set; }
        public string ProductNumber { get; set; }
        public Nullable<short> TotalQuantity { get; set; }
        public Nullable<int> CustomerMainID { get; set; }
    }
}
