//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpAccounting_BillingContractNull
    {
        public Nullable<int> ContractID { get; set; }
        public string Name { get; set; }
        public string CustID { get; set; }
        public string ServiceID { get; set; }
        public int Customer_WMS { get; set; }
        public string contractNbr { get; set; }
        public Nullable<System.DateTime> contractDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}
