//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpBillingCustomersContracts
    {
        public int BillingCustomerContractID { get; set; }
        public int BillingCustomerID { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> ServiceQuantity { get; set; }
        public string ServiceRemark { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<double> CheckingQuantity { get; set; }
        public Nullable<double> CheckingQuantity2 { get; set; }
        public bool ManualUpdate { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
