//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpBillingByOvertime
    {
        public int BillingByOverTimeID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<bool> BillingChecked { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<int> TotalPackages { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<bool> Sunday { get; set; }
        public Nullable<float> Percentage { get; set; }
    }
}
