//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpBillingReport
    {
        public int BillingDateID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public double BeginC { get; set; }
        public double BeginW { get; set; }
        public double InC { get; set; }
        public double InW { get; set; }
        public double OutC { get; set; }
        public double OutW { get; set; }
        public double CloseC { get; set; }
        public double CloseW { get; set; }
        public int CustomerID { get; set; }
        public double BeginP { get; set; }
        public double InP { get; set; }
        public double OutP { get; set; }
        public double CloseP { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> BillingCustomerID { get; set; }
        public string BillingDetailBreakdownRemark { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<decimal> InCNofee { get; set; }
        public Nullable<decimal> InWNofee { get; set; }
        public Nullable<decimal> OutCNofee { get; set; }
        public Nullable<decimal> OutWNofee { get; set; }
    }
}
