//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpBillingRunByReceivingOrders
    {
        public int RecordID { get; set; }
        public int ReceivingOrderID { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public string DispatchingOrderNumber { get; set; }
        public System.DateTime DispatchingOrderDate { get; set; }
        public Nullable<short> DispatchedQty { get; set; }
        public int ReceivingOrderDetailID { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public string CustomerRef { get; set; }
        public string SpecialRequirement { get; set; }
        public short ReceivingOrderQty { get; set; }
        public string CustomerNumber { get; set; }
        public float WeightPerPackage { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> BillingDays { get; set; }
        public string DOCustomerRef { get; set; }
        public string DOSpecialRequirement { get; set; }
        public string DORemark { get; set; }
    }
}
