//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpBillingCustomers
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<long> LimitedWeight { get; set; }
        public Nullable<long> LimitedPallet { get; set; }
        public Nullable<long> EndPreviousCarton { get; set; }
        public Nullable<double> EndPreviousWeight { get; set; }
        public Nullable<long> EndPreviousPallet { get; set; }
    }
}
