//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpCustomerSalesOrderUnitStandards
    {
        public int ProductID { get; set; }
        public string SalesProductName { get; set; }
        public string SalesUnit { get; set; }
        public Nullable<int> SalesUnitPerPackage { get; set; }
    }
}
