//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpCustomerSalesInvoiceReprt
    {
        public int ID { get; set; }
        public Nullable<int> CustomerSalesInvoiceID { get; set; }
        public Nullable<int> CustomerClientCodeFBV { get; set; }
        public string CustomerClientTaxCode { get; set; }
        public string CustomerClientTaxName { get; set; }
        public string CustomerClientAddress { get; set; }
        public string CustomerClientName { get; set; }
        public Nullable<System.DateTime> CustomerSalesInvoiceDate { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string InvoiceOfficialNumber { get; set; }
        public string InvoiceOfficialSerieName { get; set; }
        public string ProductName { get; set; }
        public string InvoiceUnit { get; set; }
        public Nullable<decimal> InvoiceQuantity { get; set; }
        public string ProductCode { get; set; }
        public string CustomerClientCode { get; set; }
        public string ProductCategoryDescription { get; set; }
        public string CustomerSalesOrderNumber { get; set; }
        public string CustomerPurchasingOrderNumber { get; set; }
        public Nullable<System.DateTime> CustomerClientCreditTerm { get; set; }
        public string PageDescription { get; set; }
        public Nullable<decimal> ProductDiscountPercentage { get; set; }
        public Nullable<decimal> InvoicePrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalDiscountAmount { get; set; }
        public string CustomerClientBuyer { get; set; }
    }
}
