//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpChart
    {
        public Nullable<int> ProductLines { get; set; }
        public Nullable<int> Pallets { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Cartons { get; set; }
        public int CustomerMainID { get; set; }
        public int ReportID { get; set; }
    }
}
