//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpDispatchingProducts
    {
        public int ID { get; set; }
        public Nullable<int> DispatchingProductID { get; set; }
        public int DispatchingOrderID { get; set; }
        public string ProductNumber { get; set; }
        public string DispatchingOrderNumber { get; set; }
        public string ProductName { get; set; }
        public int ProductID { get; set; }
        public Nullable<short> PackagesPerPallet { get; set; }
        public Nullable<int> TotalPackages { get; set; }
        public Nullable<float> WeightPerPackage { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public Nullable<byte> Status { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public string UserID { get; set; }
        public Nullable<int> Plts { get; set; }
        public string CustomerRef { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> ReceivingOrderDetailID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string LocationNumber { get; set; }
    }
}
