//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpDispatchingLocationBreak_bk2016_09_05
    {
        public int ID { get; set; }
        public int DispatchingLocationID { get; set; }
        public int DispatchingProductID { get; set; }
        public int LocationID { get; set; }
        public Nullable<short> QuantityOfPackages { get; set; }
        public Nullable<short> NewQuantityOfPackages { get; set; }
        public Nullable<bool> CheckBreak { get; set; }
        public string Label { get; set; }
        public string DispatchingLocationRemark { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<decimal> NewTotalWeight { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<int> NewTotalUnits { get; set; }
    }
}
