//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpEDIDispatchingProducts
    {
        public int DispatchingProductNewID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> DispatchingOrderDate { get; set; }
        public Nullable<int> DispatchingQuantity { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string CustomerReference { get; set; }
        public Nullable<bool> FIFO { get; set; }
    }
}
