//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpEmployeeInOutFinger
    {
        public int EmployeeInOutID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<byte> Gate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
