//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;

    public partial class tmpEmployeeOTSupervisors
    {
        public int EmployeeOTSupervisorID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string VietNamName { get; set; }
        public Nullable<float> HourQuantity { get; set; }
        public string DayStatus { get; set; }
        public Nullable<byte> GateNumber { get; set; }
        public string Remarks { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        // Interval between TimeIn and TimeOut
        public double Interval { get; set; }
    }
}
