//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpEmployeeWorkings
    {
        public int tmpEmployeeWorkingID { get; set; }
        public string OrderNumber { get; set; }
        public int Percentage { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> GeneralHandID1 { get; set; }
        public Nullable<int> GeneralHandID2 { get; set; }
        public Nullable<int> GeneralHandID3 { get; set; }
        public Nullable<int> GeneralHandID4 { get; set; }
        public Nullable<int> GeneralHandID5 { get; set; }
        public Nullable<int> WalkieID1 { get; set; }
        public Nullable<int> WalkieID2 { get; set; }
        public string TruckNo { get; set; }
        public string SealNo { get; set; }
        public string Temperature { get; set; }
        public Nullable<int> TotalPackages { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<int> PercentGH1 { get; set; }
        public Nullable<int> PercentGH2 { get; set; }
        public Nullable<int> PercentGH3 { get; set; }
        public Nullable<int> PercentGH4 { get; set; }
        public Nullable<int> PercentGH5 { get; set; }
        public string Dock { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> TimeUpdate { get; set; }
        public Nullable<int> PercentWalkieID1 { get; set; }
        public Nullable<int> PercentWalkieID2 { get; set; }
        public Nullable<bool> Approve { get; set; }
        public Nullable<int> ForkliftDriverID1 { get; set; }
        public Nullable<int> ForkliftDriverID2 { get; set; }
        public Nullable<int> PercentFD1 { get; set; }
        public Nullable<int> PercentFD2 { get; set; }
        public Nullable<int> WalkieID3 { get; set; }
        public Nullable<int> WalkieID4 { get; set; }
        public Nullable<int> PercentWalkieID3 { get; set; }
        public Nullable<int> PercentWalkieID4 { get; set; }
        public Nullable<int> TotalPercentGH { get; set; }
        public string SetupTemperature { get; set; }
    }
}
