//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpEmployeeWorkingInvalid
    {
        public int EmployeeWorkingInvalidID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Remark { get; set; }
        public string CustomerNumber { get; set; }
        public Nullable<float> TotalWeight { get; set; }
        public Nullable<float> TonOneHour { get; set; }
        public Nullable<float> Hours { get; set; }
        public string SpecialRequirement { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> NightShift { get; set; }
    }
}
