//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpEmployeeLunch
    {
        public int EmployeeLunchID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> LunchLocation { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
