//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpEmployeeWorkingDetailCheck2011
    {
        public Nullable<int> EmployeeID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<float> TotalWeight { get; set; }
        public string VietnamName { get; set; }
        public string Position { get; set; }
        public Nullable<int> CN { get; set; }
        public Nullable<int> TotalPercent { get; set; }
        public int ID { get; set; }
    }
}
