//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpElectrictyCost
    {
        public int OperatingCostMonthlyID { get; set; }
        public string OperatingCostDescription { get; set; }
        public Nullable<decimal> S1 { get; set; }
        public decimal OperatingCostDriverRate { get; set; }
        public Nullable<decimal> S2 { get; set; }
        public int OperatingCostID { get; set; }
        public int CustomerMainID { get; set; }
    }
}
