//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpFonterraBigC
    {
        public int RecordID { get; set; }
        public int CustomerMainID { get; set; }
        public System.DateTime DispatchingOrderDate { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public short TotalPackages { get; set; }
        public Nullable<float> WeightPerPackage { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string SpecialRequirement { get; set; }
        public int CustomerID { get; set; }
    }
}
