//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpFreeLocations
    {
        public string RoomID { get; set; }
        public Nullable<int> QtyLocation { get; set; }
        public Nullable<int> QtyLow { get; set; }
        public Nullable<int> QtyHigh { get; set; }
        public Nullable<int> QtyOfFree { get; set; }
        public Nullable<int> QtyFreeAfterDP { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> QtyFree_Low { get; set; }
        public Nullable<int> QtyStandards { get; set; }
        public string RoomRemark { get; set; }
        public Nullable<int> QtyFree_VeryLow { get; set; }
        public Nullable<int> QtyFree_VeryHigh { get; set; }
        public Nullable<int> QtyFree_High { get; set; }
        public Nullable<int> QtyOfPallets_OnHand { get; set; }
    }
}
