//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpLocForStockTake
    {
        public int LocationID { get; set; }
        public string LocationNumber { get; set; }
        public string RoomID { get; set; }
        public short Aisle { get; set; }
        public short Bay { get; set; }
        public short High { get; set; }
        public short Deep { get; set; }
        public short Used { get; set; }
    }
}
