//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpLocationCodes
    {
        public double LocationID { get; set; }
        public string RoomID { get; set; }
        public string LocationNumber { get; set; }
        public Nullable<double> Code { get; set; }
    }
}
