//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpMETRORandomWeight
    {
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> WeightPerPackage { get; set; }
        public Nullable<short> Inners { get; set; }
        public Nullable<int> BeginC { get; set; }
        public Nullable<double> BeginW { get; set; }
        public Nullable<int> BeginU { get; set; }
        public Nullable<int> MinRODetailID { get; set; }
    }
}
