//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpMovementHistory
    {
        public int PalletID { get; set; }
        public string MovementHistory { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
