//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpNoteDispatchingOder
    {
        public int NoteDispatchingOderID { get; set; }
        public Nullable<int> DispatchingOderID { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
        public string NoteBy { get; set; }
        public Nullable<bool> Checked { get; set; }
    }
}
