//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpNoteDispatchingOderDetail
    {
        public int NoteDispatchingOderDetailID { get; set; }
        public Nullable<int> NoteDispatchingOderID { get; set; }
        public string LinkImg { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UploadBy { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string Type { get; set; }
    }
}
