//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpPayRollAnnual
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string VietnamName { get; set; }
        public Nullable<float> TimeWorkSum { get; set; }
        public Nullable<float> OTNSum { get; set; }
        public Nullable<float> OTSSum { get; set; }
        public Nullable<float> WorkingDaySum { get; set; }
        public Nullable<float> LeaveSum { get; set; }
        public Nullable<float> OffSum { get; set; }
        public Nullable<float> SickSum { get; set; }
        public Nullable<float> HaftSum { get; set; }
        public Nullable<float> PerformanceTotal { get; set; }
        public Nullable<short> PayRollYearID { get; set; }
        public Nullable<float> OTHSum { get; set; }
    }
}
