//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpPropertyMonthly
    {
        public int ID { get; set; }
        public Nullable<int> PayRollMonthID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> Property_Begin { get; set; }
        public Nullable<int> Property_In { get; set; }
        public Nullable<int> Property_Used { get; set; }
        public Nullable<int> Property_Closing { get; set; }
    }
}
