//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpPayrollAnnualLeaveAll
    {
        public string VietnamName { get; set; }
        public int PositionID { get; set; }
        public Nullable<System.DateTime> ContractDateFirst { get; set; }
        public int ManagementLevel { get; set; }
        public bool ContractPermanent { get; set; }
        public bool Active { get; set; }
        public string VietnamPosition { get; set; }
        public Nullable<byte> Department { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IDCardNumber { get; set; }
        public string DepartmentName { get; set; }
        public int EmployeeID { get; set; }
        public string Position { get; set; }
        public Nullable<int> LEA { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public Nullable<double> LeaveAllowance { get; set; }
    }
}
