//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpRepeatRows
    {
        public int Id { get; set; }
        public string RepeatText { get; set; }
        public Nullable<int> RepeatCount { get; set; }
        public Nullable<int> QtyToCount { get; set; }
        public string CartonNumber { get; set; }
    }
}
