//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpReleaseSummary
    {
        public int tmpReleaseSummaryID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProductCategory { get; set; }
        public string ProductGroupDescription { get; set; }
        public Nullable<double> RWFD { get; set; }
        public Nullable<double> DWFD { get; set; }
        public Nullable<double> ReleaseWFD { get; set; }
        public Nullable<double> RWFDTD { get; set; }
        public Nullable<double> DWFDTD { get; set; }
        public Nullable<double> ReleaseWFDTD { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
    }
}
