//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpRoomOccupancies
    {
        public string RoomID { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<double> Occupancy { get; set; }
        public Nullable<double> OccupancyLastYear { get; set; }
        public Nullable<double> OccupancyLastMonth { get; set; }
        public Nullable<double> OccupancyPreviousMonth { get; set; }
        public string RoomProductStorage { get; set; }
    }
}
