//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpReceivingAdvices
    {
        public string CustomerNumber { get; set; }
        public int ReceivingOrderID { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public int ReceivingOrderDetailID { get; set; }
        public int ProductID { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public short OriginalQuantity { get; set; }
        public float WeightPerPackage { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public string Packages { get; set; }
        public string CustomerRef { get; set; }
        public string Label { get; set; }
        public int PalletID { get; set; }
        public string CustomerName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Total { get; set; }
        public string RoomID { get; set; }
        public string SpecialRequirement { get; set; }
    }
}
