//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpStockCorrectionProducts
    {
        public int DispatchingProductNewID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> DispatchingQuantity { get; set; }
        public Nullable<int> RemainQuantity { get; set; }
        public Nullable<decimal> TotalUnitWeight { get; set; }
        public Nullable<bool> CheckDispatched { get; set; }
        public string UserName { get; set; }
        public string SystemFeedback { get; set; }
        public byte[] ts { get; set; }
    }
}
