//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpStockOnHandByDate
    {
        public Nullable<int> CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> BeginC { get; set; }
        public Nullable<double> BeginW { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> BeginP { get; set; }
        public Nullable<double> WPP { get; set; }
        public int StockOnHandByDateID { get; set; }
        public Nullable<int> ProductLines { get; set; }
        public Nullable<int> PalletLowPercent { get; set; }
    }
}
