//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpStockOnHandTop25Customers
    {
        public int CustomerMainID { get; set; }
        public string YearMonth { get; set; }
        public Nullable<decimal> TotalPallets { get; set; }
        public Nullable<double> AverageWPP { get; set; }
        public string CustomerName { get; set; }
        public int ID { get; set; }
    }
}
