//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpScheduled_JobWeeks
    {
        public int ID { get; set; }
        public Nullable<float> Week { get; set; }
        public Nullable<System.DateTime> DateFirstOfWeek { get; set; }
        public bool CheckForChange { get; set; }
        public Nullable<int> ScheduledJobDefinitionID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public string Frequence { get; set; }
        public Nullable<float> Duration { get; set; }
    }
}
