//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpTaskBackUp
    {
        public int TaskID { get; set; }
        public int CustomerID { get; set; }
        public int ReportID { get; set; }
        public string EmployeeID { get; set; }
        public short SendVia { get; set; }
        public Nullable<int> Scheduling { get; set; }
        public Nullable<System.DateTime> LastSendTime { get; set; }
        public bool TaskResult { get; set; }
        public string TaskResultDescription { get; set; }
        public Nullable<System.DateTime> NextSendTime { get; set; }
        public string Destination { get; set; }
        public bool SendAt1800 { get; set; }
        public byte ReportFormat { get; set; }
        public byte[] TS { get; set; }
    }
}
