//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingDefinitions
    {
        public int TrainingDefinitionID { get; set; }
        public string TrainingName { get; set; }
        public string TrainingRemark { get; set; }
        public string TrainingType { get; set; }
        public Nullable<short> StandardFrequence { get; set; }
        public string DefaultTrainingLocation { get; set; }
        public Nullable<bool> isCritical { get; set; }
        public Nullable<int> TrainingGroupDefinitionID { get; set; }
    }
}
