//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportTrip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportTrip()
        {
            this.TransportTripOutsourceDetails = new HashSet<TransportTripOutsourceDetail>();
        }
    
        public int TransportTripID { get; set; }
        public string TransportTripNumber { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime TransportTripDate { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public string TransportTripRemark { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string GPSAPILink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportTripOutsourceDetail> TransportTripOutsourceDetails { get; set; }
    }
}
