//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserID { get; set; }
        public string TransactionType { get; set; }
        public string OrderNumber { get; set; }
        public string CustomerNumber { get; set; }
    }
}
