//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truck()
        {
            this.TruckOnRoadDatas = new HashSet<TruckOnRoadData>();
        }
    
        public int TruckID { get; set; }
        public string TruckNumber { get; set; }
        public string APIID { get; set; }
        public Nullable<double> Volume { get; set; }
        public string ChillFrozen { get; set; }
        public string Contracter { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LinkAPI { get; set; }
        public string UserName { get; set; }
        public string Passwords { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckOnRoadData> TruckOnRoadDatas { get; set; }
    }
}
