//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckOnRoadData
    {
        public int TruckOnRoadDataID { get; set; }
        public int TruckID { get; set; }
        public System.Data.Entity.Spatial.DbGeography TruckCoordinates { get; set; }
        public Nullable<System.DateTime> RecordedTime { get; set; }
        public Nullable<decimal> Temperature1 { get; set; }
        public Nullable<decimal> Temperature2 { get; set; }
        public Nullable<decimal> Temperature3 { get; set; }
        public string ServiceProvider { get; set; }
        public Nullable<int> TruckStatus { get; set; }
    
        public virtual Truck Truck { get; set; }
    }
}
