//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApplicationRoleGroup
    {
        public UserApplicationRoleGroup()
        {
            this.UserApplicationRoleGroupFunctions = new HashSet<UserApplicationRoleGroupFunction>();
        }
    
        public int UserApplicationRoleGroupId { get; set; }
        public Nullable<int> UserApplicationRoleId_Delete { get; set; }
        public int GroupId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<UserApplicationRoleGroupFunction> UserApplicationRoleGroupFunctions { get; set; }
    }
}
