//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApplicationActivity
    {
        public int UserApplicationActivityID { get; set; }
        public string LoginName { get; set; }
        public int EmployeeID { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationVersion { get; set; }
        public System.DateTime LoginTime { get; set; }
        public string DeviceNumber { get; set; }
        public string NetworkData { get; set; }
        public string GeographicData { get; set; }
    }
}
