//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFunctionDefinition
    {
        public int FunctionId { get; set; }
        public string FunctionName { get; set; }
        public string FunctionGroup { get; set; }
        public int GroupId { get; set; }
        public string FormName { get; set; }
        public bool IsSelected { get; set; }
    }
}
