//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFonterraCustomerClients
    {
        public int CustomerID { get; set; }
        public int CustomerClientID { get; set; }
        public string CustomerClientCode { get; set; }
        public string CustomerClientName { get; set; }
        public int CustomerSalesContractID { get; set; }
        public Nullable<int> CustomerClientMainID { get; set; }
        public Nullable<int> CustomerClientCodeFBV { get; set; }
        public string MainClientName { get; set; }
    }
}
