//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFonterraSalesContractDetails
    {
        public string CustomerClientCode { get; set; }
        public string CustomerClientName { get; set; }
        public string CustomerClientMain { get; set; }
        public Nullable<int> CustomerClientCodeFBV { get; set; }
        public string CustomerSalesContractNumber { get; set; }
        public Nullable<System.DateTime> SalesContractToDate { get; set; }
        public int ProductID { get; set; }
        public string SalesProductCode { get; set; }
        public string SalesProductCode2 { get; set; }
        public string SalesProductName { get; set; }
        public float SalesPrice { get; set; }
        public string SalesUnit { get; set; }
        public Nullable<int> SalesUnitPerPackage { get; set; }
        public Nullable<System.DateTime> SalesContractDate { get; set; }
        public Nullable<float> DiscountPercentage { get; set; }
        public string SalesContractRemark { get; set; }
        public Nullable<bool> CustomerSalesContractConfirmed { get; set; }
        public Nullable<int> CustomerClientMainID { get; set; }
        public int CustomerClientID { get; set; }
        public int CustomerSalesContractDetailID { get; set; }
        public int CustomerSalesContractID { get; set; }
    }
}
