//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMETROCalculateWeightAnnimalControl
    {
        public int CustomerID { get; set; }
        public System.DateTime DispatchingOrderDate { get; set; }
        public int TripID { get; set; }
        public string TripRemarks { get; set; }
        public string DispatchingOrderNumber { get; set; }
        public string SpecialRequirement { get; set; }
        public string CustomerClientCode { get; set; }
        public string CustomerClientName { get; set; }
        public string ProductGroupDescription { get; set; }
        public string MainGroup { get; set; }
        public string SubGroup { get; set; }
        public string Original { get; set; }
        public short TotalCtns { get; set; }
        public Nullable<float> TotalWeight { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public string GroupOriginal { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public string Supplier { get; set; }
        public string Manufactured { get; set; }
        public string DocumentFileScan { get; set; }
        public string CustomNo { get; set; }
        public string CustomerRef { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string Label { get; set; }
    }
}
