//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewWallPickingList
    {
        public int CustomerID { get; set; }
        public System.DateTime DispatchingOrderDate { get; set; }
        public string DispatchingOrderNumber { get; set; }
        public string SpecialRequirement { get; set; }
        public short TotalCtns { get; set; }
        public Nullable<float> TotalWeight { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public int CustomerMainID { get; set; }
        public string Label { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string PickingLocation { get; set; }
    }
}
