//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMETROStockOnHandForQA
    {
        public string ProductGroupDescription { get; set; }
        public string MainGroup { get; set; }
        public string SubGroup { get; set; }
        public string Original { get; set; }
        public string GroupOriginal { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public string Supplier { get; set; }
        public string Manufactured { get; set; }
        public string DocumentFileScan { get; set; }
        public string CustomNo { get; set; }
        public Nullable<int> QtyCtns { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string CustomerRef { get; set; }
        public byte ROStatus { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public string ProductNumber { get; set; }
        public int CustomerMainID { get; set; }
        public string ProductName { get; set; }
        public decimal WeightPerPackage { get; set; }
        public Nullable<short> Inners { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> QtyRemainCtns { get; set; }
        public string SpecialRequirement { get; set; }
    }
}
