//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPizzaHutDispatchingLabel
    {
        public int CustomerID { get; set; }
        public int DispatchingOrderID { get; set; }
        public Nullable<int> TotalCtns { get; set; }
        public string SpecialRequirement { get; set; }
        public string Destination { get; set; }
        public string CartonNumber { get; set; }
    }
}
