//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStockOnHandByLotAllCustomers
    {
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public float WeightPerPackage { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string CustomerRef { get; set; }
        public bool OnHold { get; set; }
        public Nullable<byte> PalletStatus { get; set; }
        public Nullable<int> OriginalQty { get; set; }
        public Nullable<int> CurrentQty { get; set; }
    }
}
