//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFonterraQA
    {
        public int CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public string SpecialRequirement { get; set; }
        public int QAReportID { get; set; }
        public string OrderNumber { get; set; }
        public string Original { get; set; }
        public string Supplier { get; set; }
        public string Manufactured { get; set; }
        public string DocumentFileScan { get; set; }
        public string CustomNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<bool> RecorderConfirmed { get; set; }
        public byte[] ts { get; set; }
        public Nullable<System.DateTime> RecorderOccurTime { get; set; }
        public string RecorderTransporterRepresentative { get; set; }
        public string RecorderTransporter { get; set; }
        public string RecorderTruckNo { get; set; }
        public string RecorderPhoneNo { get; set; }
        public string RecorderTemperature { get; set; }
        public string RecorderDriver { get; set; }
        public string RecorderCode { get; set; }
        public string RecorderProductBranch { get; set; }
        public string RecorderDescription { get; set; }
        public string ContainerNo { get; set; }
        public string Note { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> StoreNumber { get; set; }
        public int CustomerMainID { get; set; }
    }
}
