//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewConfirmationAllUnion
    {
        public string CustomerNumber { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string username { get; set; }
        public int ordertype { get; set; }
        public string typename { get; set; }
        public string ordernumber { get; set; }
        public int ID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> statusname { get; set; }
        public string customerref { get; set; }
        public int detailID { get; set; }
        public Nullable<int> transactionID { get; set; }
    }
}
