//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeTrainingManagement
    {
        public int TrainingID { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string TrainingLocation { get; set; }
        public string TrainingDescription { get; set; }
        public Nullable<int> TrainingCost { get; set; }
        public string CurrencyUnit { get; set; }
        public Nullable<decimal> TrainingDuration { get; set; }
        public string TrainingConfirmedBy { get; set; }
        public bool TrainingConfirm { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> Department { get; set; }
        public string EmployeeFeedback { get; set; }
        public string ManagerFeedback { get; set; }
        public string CostCoverBy { get; set; }
        public string DocumentFolder { get; set; }
        public Nullable<int> TrainingDefinitionID { get; set; }
        public Nullable<System.DateTime> TrainingExpiryDate { get; set; }
        public string TrainingNumber { get; set; }
        public string VietnamName { get; set; }
        public string TrainingName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    }
}
