//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTotalStockRemain
    {
        public int CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public decimal WeightPerPackage { get; set; }
        public Nullable<decimal> GrossWeightPerPackage { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public string SpecialRequirement { get; set; }
        public short TotalPackages { get; set; }
        public string Label { get; set; }
        public short OriginalQuantity { get; set; }
        public short CurrentQuantity { get; set; }
        public string CustomerRef { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public bool OnHold { get; set; }
    }
}
