//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUnileverDailyLabellingPlan
    {
        public string CustomerClientCode { get; set; }
        public string CustomerClientName { get; set; }
        public Nullable<int> Ctns { get; set; }
        public Nullable<int> Units { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime DispatchingOrderDate { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
    }
}
