//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTotalPallets
    {
        public int PalletID { get; set; }
        public string Label { get; set; }
        public Nullable<short> OriginalQuantity { get; set; }
        public Nullable<short> AfterDPQuantity { get; set; }
        public Nullable<short> CurrentQuantity { get; set; }
        public Nullable<bool> OnHold { get; set; }
        public Nullable<int> ReceivingOrderDetailID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> CanMove { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> CanNotAdd { get; set; }
        public Nullable<int> UnitQuantity { get; set; }
        public Nullable<float> PalletWeight { get; set; }
        public Nullable<byte> PalletStatus { get; set; }
    }
}
