//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewContractsAllCustomers
    {
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime ContractDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ContractRemark { get; set; }
        public string InsuranceUnit { get; set; }
        public Nullable<decimal> InsuranceUnitValue { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<byte> BillingCycle { get; set; }
        public string ServiceNumber { get; set; }
        public string ServiceName { get; set; }
        public Nullable<double> ContractServicePrice { get; set; }
        public string ContractDetailRemark { get; set; }
        public string CurrencyUnit { get; set; }
        public Nullable<double> CheckingQuantity { get; set; }
        public Nullable<double> CheckingQuantity2 { get; set; }
    }
}
