//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCustomerSalesInvoices3PL
    {
        public int Batch_Number { get; set; }
        public Nullable<long> EDI_Line_Number { get; set; }
        public string Reference__VR01_ { get; set; }
        public string Reference__VR02_ { get; set; }
        public Nullable<long> Line_Number__LNID_ { get; set; }
        public string Ship_To_Number { get; set; }
        public Nullable<System.DateTime> Order_Date__TRDJ { get; set; }
        public System.DateTime Invoice_Date__IVD_ { get; set; }
        public string C2nd_Item_Number { get; set; }
        public float Quantity_Ordered__UORG_ { get; set; }
        public string UM__UOM_ { get; set; }
        public Nullable<double> Unit_Price__UPRC_ { get; set; }
        public Nullable<double> Extended_Price { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
        public string User_ID { get; set; }
    }
}
