//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeWorkingLast45days
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int EmployeeID { get; set; }
        public string VietnamName { get; set; }
        public string VietnamPosition { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> Department { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderNumber { get; set; }
        public int Percentage { get; set; }
        public string Remark { get; set; }
        public Nullable<float> ProductionQuantity { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
