//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeEventLast30days
    {
        public bool Leave { get; set; }
        public int EmployeeID { get; set; }
        public int PayrollDetailID { get; set; }
        public System.DateTime PayrollDate { get; set; }
        public float OTS { get; set; }
        public float OTN { get; set; }
        public float OTH { get; set; }
        public bool Sick { get; set; }
        public bool Haft { get; set; }
        public string Name { get; set; }
        public bool Off { get; set; }
        public string PayrollRemark { get; set; }
        public string User { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string TimeWork { get; set; }
        public bool SunHol { get; set; }
        public Nullable<byte> Noodles { get; set; }
        public Nullable<byte> Lunch { get; set; }
        public Nullable<byte> Milk { get; set; }
        public string BenefitUser { get; set; }
        public bool LunchCompensate { get; set; }
        public string Position { get; set; }
        public string VietnamName { get; set; }
        public string VietnamPosition { get; set; }
        public Nullable<byte> Department { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentNameShort { get; set; }
        public string SystemLeave { get; set; }
        public string Shift { get; set; }
        public string ShiftGroup { get; set; }
        public Nullable<bool> NightShift { get; set; }
        public string Contract { get; set; }
        public string LunchPlace { get; set; }
        public float OTNN { get; set; }
        public float OTSN { get; set; }
        public float OTHN { get; set; }
        public float OTNN_ { get; set; }
    }
}
