//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDispatchingProductsDelete
    {
        public int DispatchingProductID { get; set; }
        public short AfterDPQuantity { get; set; }
        public Nullable<short> QuantityOfPackages { get; set; }
        public short CurrentQuantity { get; set; }
    }
}
