//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUnileverOrderstoBigC
    {
        public int DispatchingOrderID { get; set; }
        public string SpecialRequirement { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string StoreName { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<decimal> OrderWeight { get; set; }
        public Nullable<long> RowNo { get; set; }
    }
}
