//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProductMainGroup
    {
        public string ProductNumberMain { get; set; }
        public string ProductName { get; set; }
        public int CustomerID { get; set; }
        public Nullable<short> Inners { get; set; }
        public Nullable<decimal> WeightPerPackage { get; set; }
    }
}
