//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDispatchingQtyAverage30days
    {
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public short PackagesPerPallet { get; set; }
        public Nullable<int> DDates { get; set; }
        public Nullable<int> QtyTrans { get; set; }
        public Nullable<int> QtyCtns { get; set; }
        public Nullable<int> AvgDailyCtn { get; set; }
        public string RoomID { get; set; }
    }
}
