//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMETROPalletOnHandDaily
    {
        public int CustomerMainID { get; set; }
        public int DateID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public int PalletID { get; set; }
        public string Label { get; set; }
        public int LocationID { get; set; }
        public short AfterDPQuantity { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public decimal WeightPerPackage { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNumber { get; set; }
        public short CurrentQuantity { get; set; }
        public Nullable<int> CountCustomerID { get; set; }
        public Nullable<int> FirstPalletID { get; set; }
    }
}
