//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTuPhuongReceivingPallets
    {
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public string SpecialRequirement { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public string Label { get; set; }
        public short OriginalQuantity { get; set; }
        public Nullable<float> PalletWeight { get; set; }
    }
}
