//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStockTakeByRequestData
    {
        public string ReceivingOrderNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public string SpecialRequirement { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public float WeightPerPackage { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string CustomerRef { get; set; }
        public string RODetailRemark { get; set; }
        public string LocationNumber { get; set; }
        public string RoomID { get; set; }
        public short Aisle { get; set; }
        public short Bay { get; set; }
        public short High { get; set; }
        public short Deep { get; set; }
        public short OriginalQuantity { get; set; }
        public short AfterDPQuantity { get; set; }
        public short CurrentQuantity { get; set; }
        public bool OnHold { get; set; }
        public string PalletRemark { get; set; }
        public Nullable<int> StoreID { get; set; }
    }
    public partial class STPickingSlipOldOrders2_Result
    {
        public int DispatchingOrderID { get; set; }
        public string DispatchingOrderNumber { get; set; }
        public string CustomerNumber { get; set; }
        public System.DateTime DispatchingOrderDate { get; set; }
        public string CustomerName { get; set; }
        public string PP { get; set; }
        public string ProductName { get; set; }
        public string SpecialRequirement { get; set; }
        public string ProductNumber { get; set; }
        public int LocationID { get; set; }
        public string Label { get; set; }
        public Nullable<short> QtyDetails { get; set; }
        public string DispatchingLocationRemark { get; set; }
        public int DispatchingLocationID { get; set; }
        public Nullable<short> Expr1 { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public int PalletID { get; set; }
        public int ReceivingOrderID { get; set; }
        public int CustomerID { get; set; }
        public int ProductID { get; set; }
        public string CustomerRef { get; set; }
        public string PalletRemark { get; set; }
        public string ScanTime { get; set; }
        public string ScanBy { get; set; }


    }
    public partial class STFreeLocationsByRoom_Result
    {
        public string RoomID { get; set; }
        public short Aisle { get; set; }
        public int QtyFreeLocations { get; set; }
        public int QtyFreeWaitingLocations { get; set; }
        public string AisleRemark{ get; set; }
    }
}
