//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewVinmartDispatchingOrdersToday
    {
        public int CustomerID { get; set; }
        public System.DateTime DispatchingOrderDate { get; set; }
        public string SpecialRequirement { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public int PalletID { get; set; }
        public short QuantityOfPackages { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string CustomerRef { get; set; }
        public string Remark { get; set; }
        public string CustomerClientCode { get; set; }
        public string CustomerClientName { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Expr1 { get; set; }
        public string Label { get; set; }
    }
}
