//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMinhPhuCheckingOverTime
    {
        public string OrderType { get; set; }
        public int CustomerID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string ServiceNumber { get; set; }
        public string ServiceName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> TotalPackages { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public string SpecialRequirement { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string DayOfWeek { get; set; }
        public string TimeType { get; set; }
    }
}
