//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewInternalAudit
    {
        public Nullable<double> TotalLost { get; set; }
        public string ProblemCategoryDescription { get; set; }
        public int InternalAuditID { get; set; }
        public string DepartmentNameShort { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<System.DateTime> InternalAuditDate { get; set; }
        public Nullable<bool> InternalAuditConfirmed { get; set; }
        public Nullable<bool> Complained { get; set; }
        public Nullable<byte> Severity { get; set; }
        public Nullable<byte> Likehood { get; set; }
        public string Remark { get; set; }
        public string Location { get; set; }
    }
}
