//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFonterraBigCDispatchingDetailsUsedByDate
    {
        public System.DateTime DispatchingOrderDate { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string Destination { get; set; }
    }
}
