//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMETRODispatchingCartons
    {
        public int CustomerID { get; set; }
        public System.DateTime DispatchingOrderDate { get; set; }
        public string DispatchingOrderNumber { get; set; }
        public string SpecialRequirement { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public int CustomerMainID { get; set; }
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public int PalletID { get; set; }
        public Nullable<int> DispatchingCartonID { get; set; }
        public Nullable<float> CartonWeight { get; set; }
        public Nullable<int> UnitQuantity { get; set; }
        public Nullable<float> PalletWeight { get; set; }
        public Nullable<short> QuantityOfPackages { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string CustomerRef { get; set; }
        public Nullable<int> TotalUnits { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<int> Pallet_UnitQty { get; set; }
        public Nullable<float> Pallet_Weight { get; set; }
        public string DispatchingRemark { get; set; }
        public short TotalPackages { get; set; }
        public Nullable<float> WeightPerPackage { get; set; }
        public Nullable<decimal> Dispatching_TotalWeight { get; set; }
        public Nullable<int> Dispatching_TotalUnits { get; set; }
    }
}
