//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTuPhuongNumboerOfLocations
    {
        public int CustomerID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public bool VeryLowHigh { get; set; }
        public Nullable<int> QtyOfLocations { get; set; }
        public bool Low { get; set; }
    }
}
