//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCustomerSalesInvoices
    {
        public int CustomerSalesInvoiceID { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime CustomerSalesInvoiceDate { get; set; }
        public string CustomerSalesInvoiceRemark { get; set; }
        public Nullable<float> TotalAmount { get; set; }
        public Nullable<float> DiscountAmount { get; set; }
        public string CustomerSalesOrderNumber { get; set; }
        public Nullable<System.DateTime> CustomerSalesOrderDate { get; set; }
        public string InvoiceOfficialNumber { get; set; }
        public string InvoiceOfficialSerieName { get; set; }
        public string ProductName { get; set; }
        public Nullable<float> OrderQuantity { get; set; }
        public Nullable<int> DispatchedQuantity { get; set; }
        public string InvoiceUnit { get; set; }
        public float InvoicePrice { get; set; }
        public float InvoiceQuantity { get; set; }
        public string CustomerSalesInvoiceDetailRemark { get; set; }
        public string CustomerPurchasingOrderNumber { get; set; }
        public string ProductNumber { get; set; }
        public string ProductCategoryDescription { get; set; }
        public string ProductNameVN { get; set; }
        public string CustomerClientCode { get; set; }
        public string CustomerClientName { get; set; }
    }
}
