//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFonterraDispatchingOrdersToday
    {
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public string DispatchingOrderNumber { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Qty { get; set; }
        public System.DateTime DispatchingOrderDate { get; set; }
        public string SpecialRequirement { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string CustomerRef { get; set; }
        public Nullable<float> WeightPerPackage { get; set; }
        public string Label { get; set; }
    }
}
