//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewfrmFreeLocations
    {
        public string RoomID { get; set; }
        public Nullable<int> QtyLocation { get; set; }
        public int QtyLow { get; set; }
        public int QtyHigh { get; set; }
        public Nullable<int> QtyOfFree { get; set; }
        public int QtyFreeAfterDP { get; set; }
    }
}
