//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPayrollMonthlyDetails
    {
        public string PayRollMonth { get; set; }
        public string VietnamName { get; set; }
        public string FirstName { get; set; }
        public string Position { get; set; }
        public string VietnamPosition { get; set; }
        public string LunchPlace { get; set; }
        public Nullable<float> OTS { get; set; }
        public Nullable<float> OTN { get; set; }
        public Nullable<float> OTH { get; set; }
        public Nullable<float> Sick { get; set; }
        public Nullable<float> Leave { get; set; }
        public Nullable<float> Haft { get; set; }
        public Nullable<float> Off { get; set; }
        public Nullable<float> WorkingDays { get; set; }
        public Nullable<float> WorkingDayNightShift { get; set; }
        public float Performance { get; set; }
        public Nullable<float> PerformancePercent { get; set; }
        public float PerformanceAverage { get; set; }
        public Nullable<byte> DepartmentID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public string PayRollMonthlyRemark { get; set; }
        public int EmployeeID { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentNameShort { get; set; }
    }
}
