//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHaiNamProductList
    {
        public string ProductNumberShort { get; set; }
        public string ProductName { get; set; }
        public decimal WeightPerPackage { get; set; }
        public short PackagesPerPallet { get; set; }
        public Nullable<decimal> GrossWeightPerPackage { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
    }
}
