//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTotalDispatchingOrderDetails
    {
        public int DispatchingOrderDetailID { get; set; }
        public int DispatchingLocationID { get; set; }
        public int PalletID { get; set; }
        public Nullable<short> QuantityOfPackages { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<int> UnitQuantity { get; set; }
        public Nullable<float> PalletWeight { get; set; }
    }
}
