//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMETPalletConsolidationOtherCustomers
    {
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public string Label { get; set; }
        public short CurrentQuantity { get; set; }
        public int CustomerMainID { get; set; }
        public Nullable<int> TotalQtyAtLocation { get; set; }
        public int CustomerID { get; set; }
        public int PalletID { get; set; }
    }
}
