//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMetroStockByLocationOnHand
    {
        public string CustomerNumber { get; set; }
        public string CustomerName { get; set; }
        public int CustomerMainID { get; set; }
        public string ReceivingOrderNumber { get; set; }
        public Nullable<System.DateTime> ReceivingOrderDate { get; set; }
        public string SpecialRequirement { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> UseByDate { get; set; }
        public string CustomerRef { get; set; }
        public short AfterDPQuantity { get; set; }
        public short CurrentQuantity { get; set; }
        public Nullable<byte> PalletStatus { get; set; }
        public string Label { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int PalletID { get; set; }
        public decimal WeightPerPackage { get; set; }
        public Nullable<short> Inners { get; set; }
        public string Remark { get; set; }
        public string Packages { get; set; }
    }
}
