//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WavePickingDetails
    {
        public int WavePickingDetailID { get; set; }
        public int WavePickingID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> CheckDelete { get; set; }
        public byte[] ts { get; set; }
        public Nullable<int> TotalPackages { get; set; }
        public Nullable<int> TotalPallets { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string CustomerNumber { get; set; }
        public Nullable<int> TotalUnits { get; set; }
    }
}
