//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebUsers
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public int CustomerID { get; set; }
        public bool AllowEDI { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LastAccessed { get; set; }
        public string CustomerStore { get; set; }
    }
}
