//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Roles
    {
        public WMS_Roles()
        {
            this.WMS_UserApplicationRoles = new HashSet<WMS_UserApplicationRoles>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public int ApplicationId { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual ICollection<WMS_UserApplicationRoles> WMS_UserApplicationRoles { get; set; }
    }
}
