//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Applications
    {
        public WMS_Applications()
        {
            this.WMS_UserApplications = new HashSet<WMS_UserApplications>();
        }
    
        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<WMS_UserApplications> WMS_UserApplications { get; set; }
    }
}
