//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_UserApplications
    {
        public WMS_UserApplications()
        {
            this.WMS_UserApplicationRoles = new HashSet<WMS_UserApplicationRoles>();
        }
    
        public int UserApplicationId { get; set; }
        public string UserId { get; set; }
        public int ApplicationId { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastPasswordChangedDate { get; set; }
        public System.DateTime LastLockoutDate { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
        public int FailedPasswordAnswerAttemptCount { get; set; }
        public System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
    
        public virtual WMS_Applications WMS_Applications { get; set; }
        public virtual ICollection<WMS_UserApplicationRoles> WMS_UserApplicationRoles { get; set; }
        public virtual WMS_Users WMS_Users { get; set; }
    }
}
