//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_Users
    {
        public WMS_Users()
        {
            this.WMS_UserApplications = new HashSet<WMS_UserApplications>();
        }
    
        public string UserId { get; set; }
        public string Password { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<byte> WarehouseID { get; set; }
        public string DeviceNumber { get; set; }
    
        public virtual ICollection<WMS_UserApplications> WMS_UserApplications { get; set; }
    }
}
