//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMSVersions
    {
        public int VersionID { get; set; }
        public string VersionDescription { get; set; }
        public Nullable<System.DateTime> VersionDate { get; set; }
        public string VersionRemark { get; set; }
        public string VersionUpdateBy { get; set; }
        public string Application { get; set; }
    }
}
